(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g=this||self,l=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var m={},n=null;var ba="function"===typeof Uint8Array;const p="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function q(a){Object.isFrozen(a)||(p?a[p]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function r(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let t;function u(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&ba&&null!=a&&a instanceof Uint8Array){var c;void 0===c&&(c=0);if(!n){n={};for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=d.concat(b[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}c=m[c];d=Array(Math.floor(a.length/3));b=c[64]||"";for(e=f=0;f<a.length-2;f+=3){var E=
a[f],F=a[f+1];k=a[f+2];h=c[E>>2];E=c[(E&3)<<4|F>>4];F=c[(F&15)<<2|k>>6];k=c[k&63];d[e++]=""+h+E+F+k}h=0;k=b;switch(a.length-f){case 2:h=a[f+1],k=c[(h&15)<<2]||b;case 1:a=a[f],d[e]=""+c[a>>2]+c[(a&3)<<4|h>>4]+k+b}return d.join("")}}return a};function v(a,c){if(null!=a)return Array.isArray(a)||r(a)?w(a,c):c(a)}function w(a,c){if(Array.isArray(a)){var d=Array(a.length);for(let e=0;e<a.length;e++)d[e]=v(a[e],c);if(c=Array.isArray(a)){var b;p?b=a[p]:b=a.g;c=(null==b?0:b)&1}c&&q(d);return d}b={};for(d in a)b[d]=v(a[d],c);return b}function x(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=u(a);return Array.isArray(a)?w(a,x):a};let y;var B=function(a,c,d){var b=y;y=null;a||(a=b);b=this.constructor.u;a||(a=b?[b]:[]);this.j=(b?0:-1)-(this.constructor.o||0);this.g=null;this.h=a;a:{b=this.h.length;a=b-1;if(b&&(b=this.h[a],r(b))){this.l=a-this.j;this.i=b;break a}void 0!==c&&-1<c?(this.l=Math.max(c,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)a=d[c],a<this.l?(a+=this.j,(b=this.h[a])?Array.isArray(b)&&q(b):this.h[a]=z):(A(this),(b=this.i[a])?Array.isArray(b)&&q(b):this.i[a]=z)};
const z=Object.freeze(q([])),A=function(a){let c=a.l+a.j;a.h[c]||(a.i=a.h[c]={})};
var C=function(a,c,d=!1){return-1===c?null:c>=a.l?a.i?a.i[c]:void 0:d&&a.i&&a.i[c]?a.i[c]:a.h[c+a.j]},D=function(a,c,d=!1){a=C(a,c);a=null==a?a:!!a;return null==a?d:a},G=function(a,c,d,b=!1){b||c>=a.l?(A(a),a.i[c]=d):a.h[c+a.j]=d;return a},H=function(a,c){let d=0;for(let b=0;b<c.length;b++){const e=c[b];null!=C(a,e)&&(0!==d&&G(a,d,void 0,!1),d=e)}return d},I=function(a,c,d){if(-1===d)return null;a.g||(a.g={});const b=a.g[d];if(b)return b;let e=C(a,d,!1);if(null==e)return b;c=new c(e);return a.g[d]=
c},J=function(a,c){var d=ca;a.g||(a.g={});var b=a.g[c];if(!b){b=C(a,c,!1);null==b&&(b=z);b===z&&(b=q(b.slice()),G(a,c,b,!1));var e=b;b=[];for(let f=0;f<e.length;f++)b[f]=new d(e[f]);a.g[c]=b}return b};B.prototype.toJSON=function(){const a=this.h;return t?a:w(a,x)};function da(a,c){return u(c)}B.prototype.toString=function(){return this.h.toString()};function K(a,c,d){return H(a,c)===d?d:-1}var L=function(a,c,d=0){a=C(a,c);return null==a?d:a},M=function(a,c,d=""){a=C(a,c);return null==a?d:a};var ca=class extends B{constructor(a){super(a)}},N=[2,3,4];var O=class extends B{constructor(a){super(a)}};var P=class extends B{constructor(a){super(a)}};var fa=class extends B{constructor(a){super(a,-1,ea)}},ea=[6];var ha=class extends B{constructor(){super(void 0)}};var ia=class extends B{constructor(){super(void 0)}},ja=[2];var la=class extends B{constructor(a){super(a,-1,ka)}},ka=[2];var ma=class extends B{constructor(a){super(a)}};var na=class extends B{constructor(a){super(a)}};var oa=class extends B{constructor(a){super(a)}};var pa=class extends B{constructor(a){super(a)}},Q=[2,3,4,5,6,7];var R;var T=function(a,c){this.h=a===S&&c||"";this.g=qa},qa={},S={};var U=class{constructor(a,c){this.g=c===ra?a:""}};U.prototype.toString=function(){return this.g+""};var ra={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var V=function(){this.g=document||{cookie:""}};
V.prototype.set=function(a,c,d){let b,e,f,h=!1,k;"object"===typeof d&&(k=d.v,h=d.A||!1,f=d.domain||void 0,e=d.path||void 0,b=d.s);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(c))throw Error('Invalid cookie value "'+c+'"');void 0===b&&(b=-1);this.g.cookie=a+"="+c+(f?";domain="+f:"")+(e?";path="+e:"")+(0>b?"":0==b?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*b)).toUTCString())+(h?";secure":"")+(null!=k?";samesite="+k:"")};
V.prototype.get=function(a,c){const d=a+"=",b=(this.g.cookie||"").split(";");for(let e=0,f;e<b.length;e++){f=aa(b[e]);if(0==f.lastIndexOf(d,0))return f.substr(d.length);if(f==a)return""}return c};class W{constructor(){this.h=new V;this.g="";this.i=a=>{a:{let h;try{var c=a.data,d=c?JSON.parse(c):null;y=d;const k=new pa(d);y=null;h=k}catch(k){break a}if(4===H(h,Q)){var b=I(h,fa,K(h,Q,4)),e=J(b,6),f;e.length&&(f=sa(e));f={event:M(b,1)||void 0,category:M(b,2)||void 0,action:M(b,3)||void 0,label:M(b,4)||void 0,value:L(b,5)||void 0,additionalParams:f||void 0};null!=C(b,12)?(e=I(b,P,12),f.recommendations={targetPage:M(e,1),targetType:L(e,2),targetRank:L(e,3),targetIdenticalDescriptions:L(e,4),targetTitleWords:L(e,
5),targetDescriptionWords:L(e,6),experiment:M(e,7)}):f.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};null!=C(b,11)&&(b=I(b,O,11),f.practitionerType=M(b,1)||"Property not set",f.profileCreationMethod=M(b,4)||"Property not set",f.profileBadgeEmailOptIn=D(b,5)?"True":"False",f.profileFeedbackEmailOptIn=D(b,2)?"True":"False",f.profileNewsletterEmailOptIn=D(b,3)?"True":"False");window.dataLayer.push(f)}else if(3===
H(h,Q))b=I(h,la,K(h,Q,3)),f=J(b,2),f.length&&(e=sa(f)),f={event:"trackPageview",pageName:M(b,1),additionalParams:e||void 0,nonInteraction:D(b,3)||void 0,ratingsCount:L(b,4)||void 0,ratingsValue:L(b,5)||void 0},null!=C(b,6)&&(b=I(b,O,6),f.practitionerType=M(b,1)||"Property not set",f.profileCreationMethod=M(b,4)||"Property not set",f.profileBadgeEmailOptIn=D(b,5)?"True":"False",f.profileFeedbackEmailOptIn=D(b,2)?"True":"False",f.profileNewsletterEmailOptIn=D(b,3)?"True":"False"),window.dataLayer.push(f);
else if(7===H(h,Q))b=I(h,ma,K(h,Q,7)),window.dataLayer.push({parentContext:{referrer:M(b,2)||"",_ga_devsiteCookie:M(b,1)||""}});else if(6===H(h,Q))b=I(h,na,K(h,Q,6)),f=this.g,e=I(b,P,9)||new P,window.dataLayer.push({hostContext:{internalUser:M(b,1)||void 0,pageType:M(b,8)||void 0,projectName:M(b,6)||void 0,signedIn:M(b,2)||void 0,tenant:M(b,5)||void 0,thirdPartyCookieAccepted:f.length?"True":"False"},language:{machineTranslated:M(b,7)||void 0,requested:M(b,3)||void 0,served:M(b,4)||void 0},recommendations:{sourcePage:M(e,
1),sourceType:L(e,2),sourceRank:L(e,3),sourceIdenticalDescriptions:L(e,4),sourceTitleWords:L(e,5),sourceDescriptionWords:L(e,6),experiment:M(e,7)}});else if(5===H(h,Q))b=I(h,oa,K(h,Q,5)),window.dataLayer.push({originalUrlParameters:{dclid:M(b,1)||void 0,gclid:M(b,2)||void 0,utmCampaign:M(b,3)||void 0,utmContent:M(b,4)||void 0,utmMedium:M(b,5)||void 0,utmSource:M(b,6)||void 0,utmTerm:M(b,7)||void 0}});else if(2===H(h,Q)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),
event:"gtm.js"});f=document.getElementsByTagName("script")[0];e=document.createElement("script");e.async=!0;a=new T(S,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");a=a instanceof T&&a.constructor===T&&a.g===qa?a.h:"type_error:Const";if(void 0===R)if(c=null,(d=g.trustedTypes)&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:l,createScript:l,createScriptURL:l})}catch(k){g.console&&g.console.error(k.message)}R=c}else R=c;a=(c=R)?c.createScriptURL(a):a;c=new U(a,ra);a=e;a.src=c instanceof
U&&c.constructor===U?c.g:"type_error:TrustedResourceUrl";c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;(b=(d=null===(b=c.querySelector)||void 0===b?void 0:b.call(c,"script[nonce]"))?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b);f.parentNode.insertBefore(e,f)}}};window.addEventListener("message",this.i)}m(a){this.g=this.h.get("_ga_devsite")||"";var c=new ha;!1!==a?G(c,1,a):G(c,1,void 0,!1);a=this.g;""!==a?G(c,2,a):G(c,2,void 0,!1);a=new ia;a.g||(a.g={});var d=
c?c.h:c;a.g[2]=c;(c=H(a,ja))&&2!==c&&null!=d&&(a.g&&c in a.g&&(a.g[c]=void 0),G(a,c,void 0));c=G(a,2,d);if(window.parent!==window){a=window.parent;d=a.postMessage;a:{t=!0;try{var b=JSON.stringify(c.toJSON(),da);break a}finally{t=!1}b=void 0}d.call(a,b,"*")}}}W.prototype.notifyIframeReady=W.prototype.m;
function sa(a){const c={};for(const d of a){a=M(d,1);let b;M(d,K(d,N,2),void 0)?b=M(d,K(d,N,2),void 0):L(d,K(d,N,3),void 0)?b=L(d,K(d,N,3),void 0):4===H(d,N)&&(b=D(d,K(d,N,4),void 0)?"True":"False");c[a]=b}return c}var ta=W,X=["AnalyticsLibrary"],Y=g;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===ta?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=ta;}).call(this);
