(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self,l=function(a,b){a=a.split(".");var c=d;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b},n=function(a){return a};var p=new Map([]);p.set("devsite-a11y-announce",{src:"/android/js/devsite_devsite_a11y_announce_module.js"});p.set("devsite-analytics",{src:"/android/js/devsite_devsite_analytics_module.js"});p.set("devsite-analytics-scope",{src:"/android/js/devsite_devsite_analytics_scope_module.js"});p.set("devsite-anselm",{src:"/android/js/devsite_devsite_anselm_module.js"});p.set("devsite-api-getstarted",{src:"/android/js/devsite_devsite_api_getstarted_module.js"});p.set("devsite-apix",{src:"/android/js/devsite_devsite_apix_module.js"});
p.set("devsite-apix-index",{src:"/android/js/devsite_devsite_apix_index_module.js"});p.set("devsite-apix-snippets",{src:"/android/js/devsite_devsite_apix_snippets_module.js"});p.set("devsite-badger",{src:"/android/js/devsite_devsite_badger_module.js"});p.set("devsite-badge-awarded",{src:"/android/js/devsite_devsite_badge_awarded_module.js"});p.set("devsite-badge-awarder",{src:"/android/js/devsite_devsite_badge_awarder_module.js"});p.set("devsite-badge-redeemer",{src:"/android/js/devsite_devsite_badge_redeemer_module.js"});
p.set("devsite-book-nav",{src:"/android/js/devsite_devsite_book_nav_module.js"});p.set("devsite-bookmark",{src:"/android/js/devsite_devsite_bookmark_module.js"});p.set("devsite-chart",{src:"/android/js/devsite_devsite_chart_module.js"});p.set("devsite-catalog",{src:"/android/js/devsite_devsite_catalog_module.js"});p.set("devsite-code",{src:"/android/js/devsite_devsite_code_module.js"});p.set("devsite-content",{src:"/android/js/devsite_devsite_content_module.js"});p.set("devsite-codelab-catalog",{src:"/android/js/devsite_devsite_codelab_catalog_module.js"});
p.set("devsite-credentials-dialog",{src:"/android/js/devsite_devsite_credentials_dialog_module.js"});p.set("devsite-cse",{src:"/android/js/devsite_devsite_cse_module.js"});p.set("devsite-device",{src:"/android/js/devsite_devsite_device_module.js"});p.set("devsite-devprofile",{src:"/android/js/devsite_devsite_devprofile_module.js"});p.set("devsite-dialog",{src:"/android/js/devsite_devsite_dialog_module.js"});p.set("devsite-dynamic-content",{src:"/android/js/devsite_devsite_dynamic_content_module.js"});
p.set("devsite-expandable",{src:"/android/js/devsite_devsite_expandable_module.js"});p.set("devsite-expandable-nav",{src:"/android/js/devsite_devsite_expandable_nav_module.js"});p.set("devsite-extradory",{src:"/android/js/devsite_devsite_extradory_module.js"});p.set("devsite-feedback",{src:"/android/js/devsite_devsite_feedback_module.js"});p.set("devsite-filter",{src:"/android/js/devsite_devsite_filter_module.js"});p.set("devsite-footer-linkboxes",{src:"/android/js/devsite_devsite_footer_linkboxes_module.js"});
p.set("devsite-footer-promos",{src:"/android/js/devsite_devsite_footer_promos_module.js"});p.set("devsite-footer-utility",{src:"/android/js/devsite_devsite_footer_utility_module.js"});p.set("devsite-google-survey",{src:"/android/js/devsite_devsite_google_survey_module.js"});p.set("devsite-googler-buttons",{src:"/android/js/devsite_devsite_googler_buttons_module.js"});p.set("devsite-hats-survey",{src:"/android/js/devsite_devsite_hats_survey_module.js"});p.set("devsite-header",{src:"/android/js/devsite_devsite_header_module.js"});
p.set("devsite-heading-link",{src:"/android/js/devsite_devsite_heading_link_module.js"});p.set("devsite-iframe",{src:"/android/js/devsite_devsite_iframe_module.js"});p.set("devsite-info-popout",{src:"/android/js/devsite_devsite_info_popout_module.js"});p.set("devsite-jump-to",{src:"/android/js/devsite_devsite_jump_to_module.js"});p.set("devsite-jsfiddle-button",{src:"/android/js/devsite_devsite_jsfiddle_button_module.js"});p.set("devsite-language-selector",{src:"/android/js/devsite_devsite_language_selector_module.js"});
p.set("devsite-lightbox",{src:"/android/js/devsite_devsite_lightbox_module.js"});p.set("devsite-mathjax",{src:"/android/js/devsite_devsite_mathjax_module.js"});p.set("devsite-mdc",{src:"/android/js/devsite_devsite_mdc_module.js"});p.set("devsite-multiple-choice",{src:"/android/js/devsite_devsite_multiple_choice_module.js"});p.set("devsite-nav-buttons",{src:"/android/js/devsite_devsite_nav_buttons_module.js"});p.set("devsite-pagination",{src:"/android/js/devsite_devsite_pagination_module.js"});
p.set("devsite-panel",{src:"/android/js/devsite_devsite_panel_module.js"});p.set("devsite-playlist",{src:"/android/js/devsite_devsite_playlist_module.js"});p.set("devsite-playlist-earnable-badges",{src:"/android/js/devsite_devsite_playlist_earnable_badges_module.js"});p.set("devsite-playlist-summary",{src:"/android/js/devsite_devsite_playlist_summary_module.js"});p.set("devsite-product-catalog",{src:"/android/js/devsite_devsite_product_catalog_module.js"});p.set("devsite-profile-card",{src:"/android/js/devsite_devsite_profile_card_module.js"});
p.set("devsite-progress",{src:"/android/js/devsite_devsite_progress_module.js"});p.set("devsite-quiz",{src:"/android/js/devsite_devsite_quiz_module.js"});p.set("devsite-recommendations",{src:"/android/js/devsite_devsite_recommendations_module.js"});p.set("devsite-recommendations-dropdown",{src:"/android/js/devsite_devsite_recommendations_dropdown_module.js"});p.set("devsite-recommendations-sidebar",{src:"/android/js/devsite_devsite_recommendations_sidebar_module.js"});
p.set("devsite-reference-results",{src:"/android/js/devsite_devsite_reference_results_module.js"});p.set("devsite-search",{src:"/android/js/devsite_devsite_search_module.js"});p.set("devsite-select",{src:"/android/js/devsite_devsite_select_module.js"});p.set("devsite-selector",{src:"/android/js/devsite_devsite_selector_module.js"});p.set("devsite-shell",{src:"/android/js/devsite_devsite_shell_module.js"});p.set("devsite-shell-activate-button",{src:"/android/js/devsite_devsite_shell_activate_button_module.js"});
p.set("devsite-sitemask",{src:"/android/js/devsite_devsite_sitemask_module.js"});p.set("devsite-snackbar",{src:"/android/js/devsite_devsite_snackbar_module.js"});p.set("devsite-sort",{src:"/android/js/devsite_devsite_sort_module.js"});p.set("devsite-spinner",{src:"/android/js/devsite_devsite_spinner_module.js"});p.set("devsite-support-form",{src:"/android/js/devsite_devsite_support_form_module.js"});p.set("devsite-tabs",{src:"/android/js/devsite_devsite_tabs_module.js"});
p.set("devsite-theme-selector",{src:"/android/js/devsite_devsite_theme_selector_module.js"});p.set("devsite-thumb-rating",{src:"/android/js/devsite_devsite_thumb_rating_module.js"});p.set("devsite-toc",{src:"/android/js/devsite_devsite_toc_module.js"});p.set("devsite-topic",{src:"/android/js/devsite_devsite_topic_module.js"});p.set("devsite-tooltip",{src:"/android/js/devsite_devsite_tooltip_module.js"});p.set("devsite-tracking-question",{src:"/android/js/devsite_devsite_tracking_question_module.js"});
p.set("devsite-user",{src:"/android/js/devsite_devsite_user_module.js"});p.set("devsite-var",{src:"/android/js/devsite_devsite_var_module.js"});p.set("devsite-version-selector",{src:"/android/js/devsite_devsite_version_selector_module.js"});p.set("devsite-video",{src:"/android/js/devsite_devsite_video_module.js"});p.set("devsite-visibility-analytics",{src:"/android/js/devsite_devsite_visibility_analytics_module.js"});p.set("devsite-vplus",{src:"/android/js/devsite_devsite_vplus_module.js"});
p.set("devsite-wall-acknowledgement",{src:"/android/js/devsite_devsite_wall_acknowledgement_module.js"});p.set("devsite-youtube",{src:"/android/js/devsite_devsite_youtube_module.js"});p.set("google-codelab",{src:"/android/js/devsite_google_codelab_module.js"});p.set("google-codelab-about",{src:"/android/js/devsite_google_codelab_about_module.js"});p.set("google-codelab-analytics",{src:"/android/js/devsite_google_codelab_analytics_module.js"});p.set("google-codelab-step",{src:"/android/js/devsite_google_codelab_step_module.js"});
p.set("google-codelab-survey",{src:"/android/js/devsite_google_codelab_survey_module.js"});p.set("android-fully-clickable",{src:"/android/js/devsite_android_fully_clickable_module.js"});p.set("android-samples",{src:"/android/js/devsite_android_samples_module.js"});p.set("android-sticky-lesson",{src:"/android/js/devsite_android_sticky_lesson_module.js"});p.set("android-sticky-toc",{src:"/android/js/devsite_android_sticky_toc_module.js"});l("DevsiteAppAuthorizedElements",p);
l("DevsiteAppTenantCustomized",!0);var q={Ub:0,Tb:1,xb:6,vb:8,Db:12,Eb:14,Fb:17,Jb:18,Lb:21,Nb:25,ea:37,Ob:38,qa:40,Ra:45,P:47,v:50,J:52,G:62,Da:63,rb:66,hb:70,A:73,Xa:74,S:75,ob:76,za:77,Ba:80,H:81,Oa:82,xa:83,gb:85,Y:87,sa:89,jb:90,ta:91,Aa:92,N:93,Rb:94,wa:95,M:96,sb:97,B:98,D:99,Mb:100,pa:101,ya:102,nb:103,Qb:104,$:105,O:106,na:107,ca:108,bb:109,Z:110,la:111,Pb:112,pb:113,da:114,L:115,ga:116,Pa:117,Na:118,ua:119,ib:120,Bb:121,qb:122,Hb:123,wb:124,Ka:125,Ya:126,oa:127,Cb:128,Ta:129,Ua:130,ja:131,Ia:132,C:133,Ea:134,ra:135,Qa:136,
F:137,Sb:138,$a:139,zb:140,ub:141,Sa:142,Ma:143,ab:144,K:145,Wa:146,Fa:147,La:148,kb:149,ba:150,X:151,Ga:152,ka:153,ia:154,R:155,Kb:156,Ib:157,Ca:158,ha:159,I:160,T:161,aa:162,Ab:163,mb:164,fa:165,V:166,tb:167,W:168,Ja:169,Ha:170,va:171,ma:172,lb:173,Va:174,cb:175,eb:176,Za:177,fb:178,yb:179,Gb:180,U:181};var r={},t=null;var aa="function"===typeof Uint8Array;const u="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function v(a){Object.isFrozen(a)||(u?a[u]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function w(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let x;function y(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&aa&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!t){t={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),e=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var g=c.concat(e[f].split(""));r[f]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===t[k]&&(t[k]=h)}}}b=r[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(f=g=0;g<a.length-2;g+=3){var m=
a[g],C=a[g+1];k=a[g+2];h=b[m>>2];m=b[(m&3)<<4|C>>4];C=b[(C&15)<<2|k>>6];k=b[k&63];c[f++]=""+h+m+C+k}h=0;k=e;switch(a.length-g){case 2:h=a[g+1],k=b[(h&15)<<2]||e;case 1:a=a[g],c[f]=""+b[a>>2]+b[(a&3)<<4|h>>4]+k+e}return c.join("")}}return a};function z(a,b){if(null!=a)return Array.isArray(a)||w(a)?A(a,b):b(a)}function A(a,b){if(Array.isArray(a)){var c=Array(a.length);for(let f=0;f<a.length;f++)c[f]=z(a[f],b);if(b=Array.isArray(a)){var e;u?e=a[u]:e=a.g;b=(null==e?0:e)&1}b&&v(c);return c}e={};for(c in a)e[c]=z(a[c],b);return e}function B(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=y(a);return Array.isArray(a)?A(a,B):a};let D;var G=function(a){var b=ba,c=D;D=null;a||(a=c);c=this.constructor.Wb;a||(a=c?[c]:[]);this.i=(c?0:-1)-(this.constructor.Vb||0);this.g=a;a:{c=this.g.length;a=c-1;if(c&&(c=this.g[a],w(c))){this.j=a-this.i;this.h=c;break a}this.j=Number.MAX_VALUE}if(b)for(a=0;a<b.length;a++)if(c=b[a],c<this.j){c+=this.i;var e=this.g[c];e?Array.isArray(e)&&v(e):this.g[c]=E}else F(this),(e=this.h[c])?Array.isArray(e)&&v(e):this.h[c]=E};const E=Object.freeze(v([])),F=function(a){let b=a.j+a.i;a.g[b]||(a.h=a.g[b]={})};
var H=function(a,b,c=!1){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:c&&a.h&&a.h[b]?a.h[b]:a.g[b+a.i]},J=function(a,b){let c=H(a,b,!1);null==c&&(c=E);c===E&&(c=v(c.slice()),I(a,b,c,!1));return c},K=function(a,b){a=H(a,b);a=null==a?a:!!a;return null==a?!1:a},I=function(a,b,c,e=!1){e||b>=a.j?(F(a),a.h[b]=c):a.g[b+a.i]=c};G.prototype.toJSON=function(){const a=this.g;return x?a:A(a,B)};function ca(a,b){return y(b)}var M=function(){var a=L.g;x=!0;try{return JSON.stringify(a.toJSON(),ca)}finally{x=!1}};
G.prototype.toString=function(){return this.g.toString()};var N=function(a,b){a=H(a,b);return null==a?"":a};var da=function(){var a=`${GoogleDevelopersObject}`.replace("\n",""),b=O;D=a=a?JSON.parse(a):null;b=new b(a);D=null;return b},O=class extends G{getTenantId(){let a=H(this,1);return null==a?0:a}getLocale(){return N(this,2)}getInsecureHost(){return N(this,7)}},ba=[10,12,13,21];var P;var R=class{constructor(a,b){this.g=b===Q?a:""}};R.prototype.toString=function(){return this.g+""};var Q={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ea=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),fa=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var e=a[c].indexOf("="),f=null;if(0<=e){var g=a[c].substring(0,e);f=a[c].substring(e+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var S=function(a,b){this.j=this.s=this.i="";this.o=null;this.l=this.m="";this.g=!1;if(a instanceof S){this.g=void 0!==b?b:a.g;T(this,a.i);this.s=a.s;this.j=a.j;ha(this,a.o);this.m=a.m;b=a.h;var c=new U;c.i=b.i;b.g&&(c.g=new Map(b.g),c.h=b.h);ia(this,c);this.l=a.l}else a&&(c=String(a).match(ea))?(this.g=!!b,T(this,c[1]||"",!0),this.s=V(c[2]||""),this.j=V(c[3]||"",!0),ha(this,c[4]),this.m=V(c[5]||"",!0),ia(this,c[6]||"",!0),this.l=V(c[7]||"")):(this.g=!!b,this.h=new U(null,this.g))};
S.prototype.toString=function(){var a=[],b=this.i;b&&a.push(W(b,ja,!0),":");var c=this.j;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(W(b,ja,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.m)this.j&&"/"!=c.charAt(0)&&a.push("/"),a.push(W(c,"/"==c.charAt(0)?ka:la,!0));(c=this.h.toString())&&a.push("?",c);(c=this.l)&&a.push("#",W(c,ma));return a.join("")};
var T=function(a,b,c){a.i=c?V(b,!0):b;a.i&&(a.i=a.i.replace(/:$/,""))},ha=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},ia=function(a,b,c){b instanceof U?(a.h=b,na(a.h,a.g)):(c||(b=W(b,oa)),a.h=new U(b,a.g))},pa=function(a){return a instanceof S?new S(a):new S(a,void 0)},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,qa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},qa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},ja=/[#\/\?@]/g,la=/[#\?:]/g,ka=/[#\?]/g,oa=/[#\?@]/g,ma=/#/g,U=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.i&&fa(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};U.prototype.add=function(a,b){X(this);this.i=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var ra=function(a,b){X(a);b=Y(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))},sa=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,e){c.forEach(function(f){a.call(b,f,e,this)},this)},this)};var ta=function(a,b){X(a);let c=[];if("string"===typeof b)sa(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
U.prototype.set=function(a,b){X(this);this.i=null;a=Y(this,a);sa(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=ta(this,a);return 0<a.length?String(a[0]):b};
U.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var e=b[c];const g=encodeURIComponent(String(e)),h=ta(this,e);for(e=0;e<h.length;e++){var f=g;""!==h[e]&&(f+="="+encodeURIComponent(String(h[e])));a.push(f)}}return this.i=a.join("&")};
var Y=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},na=function(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,e){var f=e.toLowerCase();if(e!=f&&(ra(this,e),ra(this,f),0<c.length)){this.i=null;e=this.g;var g=e.set;f=Y(this,f);var h=c.length;if(0<h){const k=Array(h);for(let m=0;m<h;m++)k[m]=c[m];h=k}else h=[];g.call(e,f,h);this.h+=c.length}},a));a.j=b};const ua={};function va(a,b){var c=ua[a];if(void 0!==c&&(!c.u||Date.now()<=c.u+3E5))return c.p;c=new Promise((f,g)=>{b.onload=()=>f(b);b.onerror=h=>{b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});const e={u:0,p:c};c.catch(()=>e.u=+new Date);ua[a]=e;return c}
var wa=function(a){a=pa(a);const b=document.createElement("script");var c=a.toString();if(void 0===P){var e=null;var f=d.trustedTypes;if(f&&f.createPolicy){try{e=f.createPolicy("goog#html",{createHTML:n,createScript:n,createScriptURL:n})}catch(h){d.console&&d.console.error(h.message)}P=e}else P=e}c=(e=P)?e.createScriptURL(c):c;c=new R(c,Q);b.src=c instanceof R&&c.constructor===R?c.g:"type_error:TrustedResourceUrl";var g;c=(b.ownerDocument&&b.ownerDocument.defaultView||window).document;(g=(e=null===
(g=c.querySelector)||void 0===g?void 0:g.call(c,"script[nonce]"))?e.nonce||e.getAttribute("nonce")||"":"")&&b.setAttribute("nonce",g);return va(a.toString(),b)};class xa{constructor(){this.promise=new Promise(a=>{this.g=a})}};var Z=function(a="Devsite has failed to load."){throw Error(a);},za=async function(){var a=L;const b=new xa;l("__devsiteAppReadyResolver",b.g);l("__devsiteAppReadyPromise",b.promise);l("DevsiteApp.whenReady",()=>b.promise);if(J(a.g,12).length)try{await Promise.all(J(a.g,12).map(f=>{f=pa(f);const g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",f.toString());return va(f.toString(),g)}))}catch(f){Z(`Failed to load Devsite App dependencies: ${f.message}`)}const c=
d.DevsiteAppTenantCustomized?N(a.g,6):N(a.g,5);try{await wa(`${c}${ya(a)}`)}catch(f){if("en"!==a.g.getLocale()){I(a.g,2,"en");try{await wa(`${c}${N(a.g,4)}`)}catch(g){Z(`Failed to load Devsite App binary: ${g.message}`)}}else Z(`Failed to load Devsite App binary: ${f.message}`)}const e=document;if("complete"!==e.readyState&&"interactive"!==e.readyState){const f=new xa;e.addEventListener("readystatechange",()=>{"interactive"!==e.readyState&&"complete"!==e.readyState||f.g()});await f.promise}},ya=function(a){const b=
a.g.getLocale();a=N(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const L=new class{constructor(){this.h=null;this.g=new O;this.i=[];this.j=a=>{this.i.push(a)};this.m=()=>{this.l()};if(d.__globalAppLoader)return d.__globalAppLoader;try{this.g=da()}catch(a){Z("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;l("__globalAppLoader",this);l("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a))}l(){var a=document.querySelector("devsite-content");a&&(window.removeEventListener("message",this.j),a.removeEventListener("devsite-content-updated",this.m));
a=window;for(const b of this.i)a.dispatchEvent(b);this.i=[]}getEnv(){if(K(this.g,11))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){a:{var b=this.getEnv(),c=J(this.g,13),e=new URL(document.location.toString());e=new S(e.href);const f=Object.keys(q);if("PROD"!==b)for(const g of f)if(q[g]===
a&&(b=e.h.get(g),void 0!==b)){if("true"===b){a=!0;break a}if("false"===b){a=!1;break a}}a=Array.from(c).includes(a)}return a}},Aa=document.querySelector("devsite-content");Aa&&(window.addEventListener("message",L.j),Aa.addEventListener("devsite-content-updated",L.l.bind(L)));
(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return L.h||(L.h=za()),L.h})().then(()=>{d.DevsiteAppInit||Z("Failed to load Devsite App binary");K(L.g,9)?DevsiteAppFrameboxInit(M(),d.DevsiteAppAuthorizedElements):DevsiteAppInit(M(),d.DevsiteAppAuthorizedElements)});}).call(this);
