(function(_ds){var window=this;var qK=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},rK=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')},sK=function(a){var b=a.xm;a='<span class="devsite-nav-filter-match-count"> (<mark>';b=_ds.OC(new _ds.JC("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:b,XXX_1:_ds.R(_ds.Ro(1)),XXX_2:_ds.R(_ds.Ro(b))});
return(0,_ds.Q)(a+b+"</mark>)</span>")};var tK="onpointerover"in window?"pointerover":"mouseover",uK=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.B(a,"visually-hidden","",c))},BK=function(a){a.eventHandler.listen(a,"click",b=>{var c;if(!b.defaultPrevented){const e=b.target;"devsite-close-nav"===e.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})):_ds.B(a,"top-level-nav",""));if(e.hasAttribute("menu")){const f=e.getAttribute("menu");f&&vK(a,f)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(e.classList.contains("devsite-nav-toggle")||e.classList.contains("devsite-nav-title-no-path")||(null===(c=e.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.v&&(b=a.v.querySelector("[menu=_book]"))&&b.contains(e)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0}));var d;e instanceof Element&&e.matches("a.devsite-nav-title")?d=e:d=_ds.ei(e,"a","devsite-nav-title");d&&!d.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[tK,"focusin"],b=>void wK(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.v&&(vK(a,"_book")?a.removeAttribute("top-level-nav"):_ds.B(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.K.j());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.K.j()});a.eventHandler.listen(a,"scroll",()=>{_ds.B(a,"user-scrolled","")});a.eventHandler.listen(a.h,"click",()=>{xK(a)});a.m&&a.L.length&&(a.eventHandler.listen(a.m,"keyup",()=>void a.O.j()),a.eventHandler.listen(a.m,"focus",()=>void yK(a,"focus")));a.H&&a.eventHandler.listen(a.H,"click",()=>{var b;a.m&&(a.m.value="",a.m.focus());null===(b=a.H)||void 0===b?void 0:b.classList.add("hidden");zK(a);AK(a);yK(a,"click")})},DK=
function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.F=new Set(b);if(!_ds.D().hash&&c)CK(a,a.F);else{c=new _ds.bD;for(const d of a.F)_ds.aD(c,d)}},EK=async function(a){const b=await _ds.x();for(const c of a.F)b.unregisterIntersectionForElement(c)},FK=function(a){a.L=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},zK=function(a){var b;for(const c of a.L)c.classList.toggle("hidden",!(null===
(b=a.m)||void 0===b||!b.value))},AK=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a)a=c.parentElement,b=null===a||void 0===a?void 0:a.textContent,a&&b&&_ds.Jc(a,_ds.Mf.j(b))}},CK=async function(a,b){if(a.D){var c=await _ds.x(),d=new _ds.bD,e=f=>{f=f.target;_ds.aD(d,f);a.F.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,
e)}catch(g){e({target:f})}}},wK=function(a,b){b.defaultPrevented||(b=_ds.di(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ic(b,_ds.mc(_ds.bj(b.href).href)))},xK=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;_ds.wk(a.eventHandler,a,_ds.Pe,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.C.removeAttribute("animatable")});_ds.B(a,
"animatable","");b=_ds.Lc(a.j`animatable`);b(a.background,"animatable","");b(a.C,"animatable","");a.hasAttribute("collapsed")?(_ds.B(a,"aria-expanded","true",a.h),_ds.B(a,"aria-label","Hide side navigation",a.h),_ds.B(a,"data-title","Hide side navigation",a.h),a.removeAttribute("collapsed"),GK(a,"Expanded book nav")):(a.h.removeAttribute("aria-expanded"),_ds.B(a,"aria-label","Show side navigation",a.h),_ds.B(a,"data-title","Show side navigation",a.h),_ds.B(a,"collapsed",""),GK(a,"Collapsed book nav"));
await _ds.ij();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},yK=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},vK=function(a,b){let c=!1;if(a.v)for(const d of a.v.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),
c=!0):_ds.B(a,"hidden","",d);return c},HK=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.oj(_ds.D().pathname);a=`[href="${_ds.bj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},IK=function(a,b=a){b||(b=a);const c=b.querySelector(".devsite-mobile-nav-bottom");if(c){let d=c.querySelector(".devsite-nav-active");for(;d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.wk(a.eventHandler,d,"devsite-expandable-nav-transition-end",()=>{d&&_ds.B(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement}},KK=
async function(a){a.D&&(a.removeAttribute("user-scrolled"),await _ds.ij(),await JK(a),await a.T,await _ds.x(),await _ds.ij(),await JK(a))},JK=async function(a){if(a.D&&a.v){await _ds.x();var b=a.v.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await LK(a,b))}},LK=async function(a,b){if(a.D){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Mk(b,a,!0).y;await _ds.ij();c&&_ds.B(a,"user-scrolled","")}},GK=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},MK=class extends _ds.C{constructor(){super();this.D=!1;this.H=this.m=this.G=this.v=null;this.L=[];this.eventHandler=new _ds.G;this.R=()=>{};this.F=new Set;this.J=this.M=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.h=_ds.M(qK);this.C=_ds.M(rK);this.T=new Promise(a=>{this.R=a});this.K=new _ds.sk(()=>{this.D&&uK(this)},20);this.O=new _ds.sk(()=>{var a,b,c,d,
e,f,g,h;zK(this);AK(this);const k=null===(b=null===(a=this.m)||void 0===a?void 0:a.value)||void 0===b?void 0:b.trim().toLowerCase();if(k){null===(c=this.H)||void 0===c?void 0:c.classList.remove("hidden");for(const m of this.L){c=m.querySelectorAll(".devsite-nav-text");b=m.classList.contains("devsite-nav-expandable");var l=d=!1;a=0;if(k&&b&&(null===(f=null===(e=m.querySelector(".devsite-nav-text"))||void 0===e?void 0:e.textContent)||void 0===f?0:f.toLowerCase().includes(k)))l=d=!0;else for(const n of c)k&&
(null===(g=n.textContent)||void 0===g?0:g.toLowerCase().includes(k))&&(d=!0,++a);if(!0===d){m.classList.remove("hidden");if(l){c=Array.from(m.querySelectorAll(".devsite-nav-item"));for(const n of c)n.classList.remove("hidden"),k&&(null===(h=n.textContent)||void 0===h?0:h.toLowerCase().includes(k))&&++a}c=void 0;(l=m.querySelector(".devsite-nav-text"))&&(d=null===(c=l.textContent)||void 0===c?void 0:c.replace(new RegExp(`(${k})`,"ig"),"<mark>$1</mark>"))&&_ds.Jc(l,_ds.Mf.j(d))}b&&0<a&&(b=m.querySelector(".devsite-nav-text"))&&
(a=_ds.M(sK,{xm:a}),b.appendChild(a))}}else null===(d=this.H)||void 0===d?void 0:d.classList.add("hidden")},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){var a,b;this.D=!0;_ds.Mg(this,this.j`animatable`,this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`role`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);_ds.B(this,"role","menu");this.parentNode&&
this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.B(this,"hidden","",this.h),_ds.B(this,"hidden","",this.C));const c=await _ds.x();if(this.M=c.hasFlagAccess(150))null===(a=this.parentElement)||void 0===a?void 0:a.insertBefore(this.h,this.nextSibling),_ds.B(this,"aria-label","Hide side navigation",this.h),_ds.B(this,"data-title","Hide side navigation",this.h),_ds.B(this,"aria-expanded","true",this.h),null===(b=this.parentElement)||void 0===b?void 0:b.insertBefore(this.C,
this.nextSibling);if(this.J=c.hasFlagAccess(155))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.m=this.G.querySelector("input[type=text]"),this.H=this.G.querySelector(".filter-clear-button"),FK(this);uK(this);BK(this);await this.init();DK(this)}disconnectedCallback(){this.D=!1;_ds.J(this.eventHandler);EK(this);this.F.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.B(this,"visually-hidden","",a);a=[this.background,this.h,this.C];for(const b of a)b&&_ds.Oh(b);this.removeAttribute("animatable");
this.background.removeAttribute("animatable");this.C.removeAttribute("animatable");this.C.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):
_ds.B(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.h,this.C];for(const d of c)d&&(b?_ds.B(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.R()}async init(a=!0){if(this.D){this.C.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.v=this.querySelector(".devsite-mobile-nav-bottom");_ds.B(this,"top-level-nav","");this.v&&this.v.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");
0===this.children.length&&_ds.B(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.B(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(HK(this),IK(this),await KK(this)):(await _ds.ij(),await JK(this))}}async Ua(a){var b;a?(a=a.querySelector("nav")||null,HK(this,a),IK(this,a),a&&(await EK(this),this.F.clear(),DK(this,a,!1)),_ds.Pg(this,this.querySelector("nav"),a)):_ds.Mh(this);this.J&&(FK(this),this.m&&(this.m.value="",null===(b=
this.H)||void 0===b?void 0:b.classList.add("hidden")));await _ds.ij();await this.init(!1)}};MK.prototype.updateContent=MK.prototype.Ua;MK.prototype.attributeChangedCallback=MK.prototype.attributeChangedCallback;MK.prototype.disconnectedCallback=MK.prototype.disconnectedCallback;MK.prototype.connectedCallback=MK.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",MK)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
