(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var oR=_ds.Zg(function(){return!_ds.Ed||0<=_ds.Ha(_ds.oF,9)}),pR=_ds.Zg(function(){return _ds.Kd||_ds.Hd||_ds.Jd&&0<=_ds.Ha(_ds.oF,10)||_ds.Ed&&0<=_ds.Ha(_ds.oF,10)}),rR=function(a,b){oR()&&(b=pR()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Ck(a,qR(),b))},qR=_ds.Zg(function(){return _ds.Ed&&9==_ds.ae?"-ms-transform":"transform"});var uR=function(a){a.m=sR(a,".devsite-top-logo-row-wrapper-wrapper");a.h=sR(a,".devsite-collapsible-section");a.v=sR(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.m}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);tR(a)},tR=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.Ck(b,"transform",`translate3d(0, -${a.offset}px, 0)`),vR(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},wR=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.J(a.F);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.kh(b.offsetWidth,b.offsetHeight);b=new _ds.kh(c.offsetWidth,c.offsetHeight);var f=_ds.Vk(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Ck(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});rR(c,a.hasAttribute("search-active")?0:e);_ds.wk(a.F,d,_ds.Pe,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),rR(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(oR()){var m=pR()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.Ck(d,qR(),m)}rR(c,k)})}},xR=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null===a||void 0===a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.ij(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},zR=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.W;_ds.ei(b.target,null,"devsite-top-logo-row-middle",void 0)&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>yR(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{yR(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},AR=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},vR=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},yR=function(a){window.requestAnimationFrame(()=>
a.L.j())},sR=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},BR=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},CR=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Pg(a,c,b))},DR=class extends _ds.C{constructor(){super(...arguments);this.eventHandler=new _ds.G;this.G=
-1;this.F=new _ds.G;this.D=0;this.H=new MutationObserver(()=>uR(this));this.L=new _ds.sk(()=>{uR(this);vR(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.m=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;tR(this);break;case "search-active":wR(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),xR(this,a)}}connectedCallback(){zR(this);AR(this);vR(this);uR(this);this.H.observe(this,{childList:!0,subtree:!0});tR(this);const a=_ds.D();this.authUser=_ds.Ki(_ds.Li(a.href),"authuser")}disconnectedCallback(){_ds.J(this.eventHandler);this.H.disconnect()}C(){return this.m+this.h-this.offset}J(){return this.m+this.h}Ua(a){if(this.Jf(a||null)){this.updated=!1;
if(a){CR(this,a,".devsite-header-upper-tabs");CR(this,a,".devsite-collapsible-section");CR(this,a,".devsite-product-name-wrapper");CR(this,a,"devsite-language-selector");CR(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&BR(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(BR(c,b),c=_ds.D(),c=_ds.Ki(_ds.Li(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Pg(this,this.querySelector("cloudx-additional-tabs"),
a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.Pg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Mh(this),this.appendChild(a))}AR(this);yR(this)}};try{window.customElements.define("devsite-header",DR)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
