(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h=this||self,l=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var m={},n=null;var ba="function"===typeof Uint8Array;const p="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function q(a,c){Object.isFrozen(a)||(p?a[p]|=c:void 0!==a.g?a.g|=c:Object.defineProperties(a,{g:{value:c,configurable:!0,writable:!0,enumerable:!1}}))}function r(a){if(!a)return 0;let c;p?c=a[p]:c=a.g;return null==c?0:c}function t(a){if(!Array.isArray(a))return a;q(a,1);return a}function u(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");q(a,2)};function v(a){return null!==a&&"object"===typeof a&&a.constructor===Object}
function w(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(ba&&null!=a&&a instanceof Uint8Array){var c;void 0===c&&(c=0);if(!n){n={};for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=d.concat(b[e].split(""));m[e]=f;for(var g=0;g<f.length;g++){var k=f[g];void 0===n[k]&&(n[k]=g)}}}c=m[c];d=Array(Math.floor(a.length/3));b=c[64]||"";for(e=f=0;f<a.length-2;f+=3){var F=a[f],G=a[f+1];k=
a[f+2];g=c[F>>2];F=c[(F&3)<<4|G>>4];G=c[(G&15)<<2|k>>6];k=c[k&63];d[e++]=""+g+F+G+k}g=0;k=b;switch(a.length-f){case 2:g=a[f+1],k=c[(g&15)<<2]||b;case 1:a=a[f],d[e]=""+c[a>>2]+c[(a&3)<<4|g>>4]+k+b}a=d.join("")}return a;default:return a}}let x;function y(a,c){if(null!=a)return Array.isArray(a)||v(a)?z(a,c):c(a)}function z(a,c){if(Array.isArray(a)){var d=Array(a.length);for(var b=0;b<a.length;b++)d[b]=y(a[b],c);r(a)&1&&t(d);return d}d={};for(b in a)d[b]=y(a[b],c);return d};let A;var D=function(a,c,d){var b=A;A=null;a||(a=b);b=this.constructor.u;a||(a=b?[b]:[]);this.j=(b?0:-1)-(this.constructor.o||0);this.g=null;this.h=a;a:{b=this.h.length;a=b-1;if(b&&(b=this.h[a],v(b))){this.l=a-this.j;this.i=b;break a}void 0!==c&&-1<c?(this.l=Math.max(c,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)a=d[c],a<this.l?(a+=this.j,(b=this.h[a])?t(b):this.h[a]=B):(C(this),(b=this.i[a])?t(b):this.i[a]=B)};
const B=Object.freeze(t([])),C=function(a){let c=a.l+a.j;a.h[c]||(a.i=a.h[c]={})};var E=function(a,c,d=!1){return-1===c?null:d||c>=a.l?a.i?a.i[c]:void 0:a.h[c+a.j]},H=function(a,c,d=!1){a=E(a,c);a=null==a?a:!!a;return null==a?d:a},I=function(a,c,d,b=!1){b||c>=a.l?(C(a),a.i[c]=d):a.h[c+a.j]=d;return a};function ca(a,c,d,b){d!==b?I(a,c,d):I(a,c,void 0);return a}
var J=function(a,c){let d=0;for(let b=0;b<c.length;b++){let e=c[b];null!=E(a,e)&&(0===d||I(a,d,void 0),d=e)}return d},K=function(a,c,d){if(-1===d)return null;a.g||(a.g={});const b=a.g[d];if(b)return b;let e=E(a,d,!1);if(null==e)return b;c=new c(e);return a.g[d]=c},ea=function(a,c){var d=da;a.g||(a.g={});var b=a.g[c];if(!b){b=E(a,c,!1);null==b&&(b=B);b===B&&(b=t([]),I(a,c,b,!1));var e=b;b=[];const f=Array.isArray(e)?!!(r(e)&2):!1;for(let g=0;g<e.length;g++)b[g]=new d(e[g]),f&&u(b[g].h);f&&(u(b),Object.freeze(b));
a.g[c]=b}return b};D.prototype.toJSON=function(){const a=L(this);return x?a:z(a,w)};var L=function(a){if(a.g)for(let c in a.g){const d=a.g[c];if(Array.isArray(d))for(let b=0;b<d.length;b++)d[b]&&L(d[b]);else d&&L(d)}return a.h};function fa(a,c){return w(c)}D.prototype.toString=function(){return L(this).toString()};function M(a,c,d){return J(a,c)===d?d:-1}var N=function(a,c,d=0){a=E(a,c);return null==a?d:a},O=function(a,c,d=""){a=E(a,c);return null==a?d:a};var da=class extends D{constructor(a){super(a)}},P=[2,3,4];var ha=class extends D{constructor(a){super(a)}};var Q=class extends D{constructor(a){super(a)}};var ja=class extends D{constructor(a){super(a,-1,ia)}},ia=[6];var ka=class extends D{constructor(){super(void 0)}};var la=class extends D{constructor(){super(void 0)}},ma=[2];var oa=class extends D{constructor(a){super(a,-1,na)}},na=[2];var pa=class extends D{constructor(a){super(a)}};var qa=class extends D{constructor(a){super(a)}};var ra=class extends D{constructor(a){super(a)}};var sa=class extends D{constructor(a){super(a)}},R=[2,3,4,5,6,7];var S;var T=function(a,c){this.h=a===ta&&c||"";this.g=ua},ua={},ta={};var U=class{constructor(a,c){this.g=c===va?a:""}};U.prototype.toString=function(){return this.g+""};var va={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var V=function(){this.g=document||{cookie:""}};
V.prototype.set=function(a,c,d){let b,e,f,g=!1,k;"object"===typeof d&&(k=d.v,g=d.A||!1,f=d.domain||void 0,e=d.path||void 0,b=d.s);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(c))throw Error('Invalid cookie value "'+c+'"');void 0===b&&(b=-1);this.g.cookie=a+"="+c+(f?";domain="+f:"")+(e?";path="+e:"")+(0>b?"":0==b?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*b)).toUTCString())+(g?";secure":"")+(null!=k?";samesite="+k:"")};
V.prototype.get=function(a,c){const d=a+"=",b=(this.g.cookie||"").split(";");for(let e=0,f;e<b.length;e++){f=aa(b[e]);if(0==f.lastIndexOf(d,0))return f.substr(d.length);if(f==a)return""}return c};class W{constructor(){this.h=new V;this.g="";this.i=a=>{a:{let g;try{var c=a.data,d=c?JSON.parse(c):null;A=d;const k=new sa(d);A=null;g=k}catch(k){break a}if(4===J(g,R)){var b=K(g,ja,M(g,R,4)),e=ea(b,6),f;e.length&&(f=wa(e));f={event:O(b,1)||void 0,category:O(b,2)||void 0,action:O(b,3)||void 0,label:O(b,4)||void 0,value:N(b,5)||void 0,additionalParams:f||void 0};null!=E(b,12)?(e=K(b,Q,12),f.recommendations={targetPage:O(e,1),targetType:N(e,2),targetRank:N(e,3),targetIdenticalDescriptions:N(e,4),targetTitleWords:N(e,
5),targetDescriptionWords:N(e,6),experiment:O(e,7)}):f.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};null!=E(b,11)&&(b=K(b,ha,11),f.practitionerType=O(b,1)||"Property not set",f.profileCreationMethod=O(b,4)||"Property not set",f.profileBadgeEmailOptIn=H(b,5)?"True":"False",f.profileFeedbackEmailOptIn=H(b,2)?"True":"False",f.profileNewsletterEmailOptIn=H(b,3)?"True":"False");window.dataLayer.push(f)}else if(3===
J(g,R))b=K(g,oa,M(g,R,3)),f=ea(b,2),f.length&&(e=wa(f)),f={event:"trackPageview",pageName:O(b,1),additionalParams:e||void 0,nonInteraction:H(b,3)||void 0,ratingsCount:N(b,4)||void 0,ratingsValue:N(b,5)||void 0},null!=E(b,6)&&(b=K(b,ha,6),f.practitionerType=O(b,1)||"Property not set",f.profileCreationMethod=O(b,4)||"Property not set",f.profileBadgeEmailOptIn=H(b,5)?"True":"False",f.profileFeedbackEmailOptIn=H(b,2)?"True":"False",f.profileNewsletterEmailOptIn=H(b,3)?"True":"False"),window.dataLayer.push(f);
else if(7===J(g,R))b=K(g,pa,M(g,R,7)),window.dataLayer.push({parentContext:{referrer:O(b,2)||"",_ga_devsiteCookie:O(b,1)||""}});else if(6===J(g,R))b=K(g,qa,M(g,R,6)),f=this.g,e=K(b,Q,9)||new Q,window.dataLayer.push({hostContext:{internalUser:O(b,1)||void 0,pageType:O(b,8)||void 0,projectName:O(b,6)||void 0,signedIn:O(b,2)||void 0,tenant:O(b,5)||void 0,thirdPartyCookieAccepted:f.length?"True":"False"},language:{machineTranslated:O(b,7)||void 0,requested:O(b,3)||void 0,served:O(b,4)||void 0},recommendations:{sourcePage:O(e,
1),sourceType:N(e,2),sourceRank:N(e,3),sourceIdenticalDescriptions:N(e,4),sourceTitleWords:N(e,5),sourceDescriptionWords:N(e,6),experiment:O(e,7)}});else if(5===J(g,R))b=K(g,ra,M(g,R,5)),window.dataLayer.push({originalUrlParameters:{dclid:O(b,1)||void 0,gclid:O(b,2)||void 0,utmCampaign:O(b,3)||void 0,utmContent:O(b,4)||void 0,utmMedium:O(b,5)||void 0,utmSource:O(b,6)||void 0,utmTerm:O(b,7)||void 0}});else if(2===J(g,R)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),
event:"gtm.js"});f=document.getElementsByTagName("script")[0];e=document.createElement("script");e.async=!0;a=new T(ta,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");a=a instanceof T&&a.constructor===T&&a.g===ua?a.h:"type_error:Const";if(void 0===S)if(c=null,(d=h.trustedTypes)&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:l,createScript:l,createScriptURL:l})}catch(k){h.console&&h.console.error(k.message)}S=c}else S=c;a=(c=S)?c.createScriptURL(a):a;c=new U(a,va);a=e;a.src=c instanceof
U&&c.constructor===U?c.g:"type_error:TrustedResourceUrl";c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;(b=(d=null===(b=c.querySelector)||void 0===b?void 0:b.call(c,"script[nonce]"))?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b);f.parentNode.insertBefore(e,f)}}};window.addEventListener("message",this.i)}m(a){this.g=this.h.get("_ga_devsite")||"";var c=new ka;a=ca(c,1,a,!1);var d=ca(a,2,this.g,"");a=new la;a.g||(a.g={});c=d?L(d):d;a.g[2]=d;(d=J(a,ma))&&2!==d&&
null!=c&&(a.g&&d in a.g&&(a.g[d]=void 0),I(a,d,void 0));a=I(a,2,c);if(window.parent!==window){c=window.parent;d=c.postMessage;a:{x=!0;try{var b=JSON.stringify(a.toJSON(),fa);break a}finally{x=!1}b=void 0}d.call(c,b,"*")}}}W.prototype.notifyIframeReady=W.prototype.m;function wa(a){const c={};for(const d of a){a=O(d,1);let b;O(d,M(d,P,2),void 0)?b=O(d,M(d,P,2),void 0):N(d,M(d,P,3),void 0)?b=N(d,M(d,P,3),void 0):4===J(d,P)&&(b=H(d,M(d,P,4),void 0)?"True":"False");c[a]=b}return c}
var xa=W,X=["AnalyticsLibrary"],Y=h;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===xa?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=xa;}).call(this);
