(function(_ds){var window=this;var DX=function(a){var b=a.$g,c=a.Bb,d=a.Yk;a=a.hm;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.iq("Mostrar/ocultar contenido"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=b[h];e+='<li class="devsite-nav-item"'+
(c&&g.index<a?" visible":"")+'><a href="#'+_ds.S(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.S(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.S(h)+'" track-metadata-link-destination="#'+_ds.S(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(g.text)+"</span></a>";if(_ds.Yp(g.children).length){e+='<ul class="devsite-nav-list">';
g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.S(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.S(h)+"."+_ds.S(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.S(h)+"."+_ds.S(l)+'" track-metadata-link-destination="#'+
_ds.S(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Probar</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Probar</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.iq("Mostrar/ocultar contenido"),e+='"></button></li>');return(0,_ds.Q)(e+"</ul>")};var FX=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Bb?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),EX(a,b),a.H=!0):a.ib()}},HX=async function(a){await GX(a);if(a.h){var b=`#${a.h.id}`,c=encodeURI(b);b=a.F.get(b)||a.F.get(c);a.v!==b&&(a.v&&a.v.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.v=b))}},IX=function(a){a.Bb||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
()=>{a.K.j()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{FX(a)})},JX=async function(a){if("IntersectionObserver"in _ds.Ah()){a.C&&a.C.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await window.customElements.whenDefined("devsite-header"),(b=Number(b.getAttribute("top-row--height"))+Number(b.getAttribute("bottom-row--height")))&&(c=b));a.C=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.D.add(e.target):a.D.delete(e.target);a.K.j()},
{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.J.j()},GX=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),b=c.C());c=a.m.findIndex(e=>a.D.has(e)&&e.getBoundingClientRect().top>=b);const d=a.m[c];if(d){const e=await KX();d.getBoundingClientRect().top-b>e&&0<c?a.h=a.m[c-1]:a.h=d}else a.h&&a.h.getBoundingClientRect().top>window.innerHeight&&(c=a.m.indexOf(a.h),0<c&&(a.h=a.m[c-1]))},EX=function(a,b){const c=[];
let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.m=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>LX(f));for(const [f,g]of a.m.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-
1].children.push(b):c.push(b);_ds.Ya(a.G,c,a.L.bind(a))&&a.H||(c.length?(MX(a,c),a.show(),a.Bb||NX(a)):a.ib(),a.G=c)},LX=function(a){return _ds.kj.find(b=>!!_ds.Yh(a,null,b,6))||_ds.Yh(a,"devsite-selector",null,6)||_ds.Yh(a,null,"devsite-dialog",3)?!1:!0},MX=function(a,b){const c=_ds.M(DX,{$g:b,Bb:a.Bb,Yk:!!document.body.querySelector("devsite-apix, .devsite-apix"),hm:8>b.length?8:5});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.F.set(e,b);
a.F.set(f,b)}_ds.Fh(a);a.Bb&&_ds.A(a,"hidden","",c);a.appendChild(c);if(a.Bb){if(8<a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.A(a,"expanded","")});_ds.A(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},0)}},NX=async function(a){await a.J.promise;if(a.C){a.C.disconnect();
a.D.clear();a.v&&a.v.classList.remove("devsite-nav-active");a.v=null;for(const b of a.m)a.C.observe(b)}},KX=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),a=c.C(),b=c.J());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},OX=class extends _ds.C{constructor(){super();this.eventHandler=new _ds.H;this.J=new _ds.rk;this.D=new Set;this.F=new Map;this.R=new _ds.lk(()=>void FX(this),16);this.K=new _ds.lk(()=>
void HX(this),33);this.h=this.v=null;this.m=[];this.H=!1;this.C=null;this.Bb=!1;this.G=[];_ds.Fg(this,(0,_ds.u)`disabled`,(0,_ds.u)`has-sidebar`,(0,_ds.u)`hidden`,(0,_ds.u)`expandable`,(0,_ds.u)`expanded`,(0,_ds.u)`visible`)}static get observedAttributes(){return["max-height","offset"]}connectedCallback(){this.Bb=this.hasAttribute("devsite-toc-embedded");FX(this);IX(this)}disconnectedCallback(){this.ib();this.H=!1;_ds.K(this.eventHandler)}Fe(a){a=a&&"false"===a.toLowerCase();this.G=[];_ds.Fh(this);
a?(_ds.A(this,"disabled",""),this.ib()):(this.removeAttribute("disabled"),this.show(),this.R.j())}ib(){_ds.Fh(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.A(this,"hidden","");if(!this.Bb){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.A(this,"visible","");if(!this.Bb){const a=
document.querySelector(".devsite-main-content");a&&_ds.A(this,"has-sidebar","",a);JX(this)}}L(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.Ya(a.children,b.children,this.L.bind(this));return c&&a.id===b.id&&a.text===b.text}};OX.prototype.renderUpdatedContent=OX.prototype.Fe;OX.prototype.disconnectedCallback=OX.prototype.disconnectedCallback;OX.prototype.connectedCallback=OX.prototype.connectedCallback;try{window.customElements.define("devsite-toc",OX)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
