(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var eR=_ds.Sg(function(){return!_ds.wd||0<=_ds.ya(_ds.dF,9)}),fR=_ds.Sg(function(){return _ds.Ad||_ds.xd||_ds.zd&&0<=_ds.ya(_ds.dF,10)||_ds.wd&&0<=_ds.ya(_ds.dF,10)}),hR=function(a,b){eR()&&(b=fR()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.vk(a,gR(),b))},gR=_ds.Sg(function(){return _ds.wd&&9==_ds.Td?"-ms-transform":"transform"});var kR=function(a){a.m=iR(a,".devsite-top-logo-row-wrapper-wrapper");a.h=iR(a,".devsite-collapsible-section");a.v=iR(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.m}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);jR(a)},jR=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.vk(b,"transform",`translate3d(0, -${a.offset}px, 0)`),lR(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},mR=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.K(a.H);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.dh(b.offsetWidth,b.offsetHeight);b=new _ds.dh(c.offsetWidth,c.offsetHeight);var f=_ds.Ok(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.vk(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});hR(c,a.hasAttribute("search-active")?0:e);_ds.pk(a.H,d,_ds.He,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),hR(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(eR()){var m=fR()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.vk(d,gR(),m)}hR(c,k)})}},nR=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null===a||void 0===a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.bj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},pR=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.W;_ds.Yh(b.target,null,"devsite-top-logo-row-middle",void 0)&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>oR(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{oR(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},qR=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},lR=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},oR=function(a){window.requestAnimationFrame(()=>
a.L.j())},iR=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},rR=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},sR=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Ig(a,c,b))},tR=class extends _ds.C{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.G=
-1;this.H=new _ds.H;this.D=0;this.F=new MutationObserver(()=>kR(this));this.L=new _ds.lk(()=>{kR(this);lR(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.m=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;jR(this);break;case "search-active":mR(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),nR(this,a)}}connectedCallback(){pR(this);qR(this);lR(this);kR(this);this.F.observe(this,{childList:!0,subtree:!0});jR(this);const a=_ds.D();this.authUser=_ds.Ci(_ds.Ei(a.href),"authuser")}disconnectedCallback(){_ds.K(this.eventHandler);this.F.disconnect()}C(){return this.m+this.h-this.offset}J(){return this.m+this.h}Ta(a){this.updated=!1;if(a){sR(this,a,".devsite-header-upper-tabs");
sR(this,a,".devsite-collapsible-section");sR(this,a,".devsite-product-name-wrapper");sR(this,a,"devsite-language-selector");sR(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&rR(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(rR(c,b),c=_ds.D(),c=_ds.Ci(_ds.Ei(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Ig(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Ig(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Fh(this),this.appendChild(a));qR(this);oR(this)}};try{window.customElements.define("devsite-header",tR)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
