(function(_ds){var window=this;var fK=function(a){const b=new _ds.pC;return _ds.vC(b,a)};var gK=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},hK=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')},iK=function(a){var b=a.wm;a='<span class="devsite-nav-filter-match-count"> (<mark>';b=_ds.HC(new _ds.CC("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:b,XXX_1:_ds.R(fK(1)),XXX_2:_ds.R(fK(b))});
return(0,_ds.Q)(a+b+"</mark>)</span>")};var jK="onpointerover"in window?"pointerover":"mouseover",kK=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.A(a,"visually-hidden","",c))},rK=function(a){a.eventHandler.listen(a,"click",b=>{var c;if(!b.defaultPrevented){const e=b.target;"devsite-close-nav"===e.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})):_ds.A(a,"top-level-nav",""));if(e.hasAttribute("menu")){const f=e.getAttribute("menu");f&&lK(a,f)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(e.classList.contains("devsite-nav-toggle")||e.classList.contains("devsite-nav-title-no-path")||(null===(c=e.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.v&&(b=a.v.querySelector("[menu=_book]"))&&b.contains(e)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0}));var d;e instanceof Element&&e.matches("a.devsite-nav-title")?d=e:d=_ds.Yh(e,"a","devsite-nav-title");d&&!d.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[jK,"focusin"],b=>void mK(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.v&&(lK(a,"_book")?a.removeAttribute("top-level-nav"):_ds.A(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.K.j());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.K.j()});a.eventHandler.listen(a,"scroll",()=>{_ds.A(a,"user-scrolled","")});a.eventHandler.listen(a.h,"click",()=>{nK(a)});a.m&&a.L.length&&(a.eventHandler.listen(a.m,"keyup",()=>{var b,c,d,e,f,g,h,k;oK(a);pK(a);const l=null===(c=null===(b=a.m)||void 0===b?void 0:b.value)||void 0===c?void 0:c.trim().toLowerCase();if(l){null===(d=a.H)||void 0===d?void 0:d.classList.remove("hidden");for(const n of a.L){d=n.querySelectorAll(".devsite-nav-text");
c=n.classList.contains("devsite-nav-expandable");var m=e=!1;b=0;if(l&&c&&(null===(g=null===(f=n.querySelector(".devsite-nav-text"))||void 0===f?void 0:f.textContent)||void 0===g?0:g.toLowerCase().includes(l)))m=e=!0;else for(const t of d)l&&(null===(h=t.textContent)||void 0===h?0:h.toLowerCase().includes(l))&&(e=!0,++b);if(!0===e){n.classList.remove("hidden");if(m){d=Array.from(n.querySelectorAll(".devsite-nav-item"));for(const t of d)t.classList.remove("hidden"),l&&(null===(k=t.textContent)||void 0===
k?0:k.toLowerCase().includes(l))&&++b}d=void 0;(m=n.querySelector(".devsite-nav-text"))&&(e=null===(d=m.textContent)||void 0===d?void 0:d.replace(new RegExp(`(${l})`,"ig"),"<mark>$1</mark>"))&&_ds.Bc(m,_ds.If.j(e))}c&&0<b&&(c=n.querySelector(".devsite-nav-text"))&&(b=_ds.M(iK,{wm:b}),c.appendChild(b))}}else null===(e=a.H)||void 0===e?void 0:e.classList.add("hidden")}),a.eventHandler.listen(a.m,"focus",()=>void qK(a,"focus")));a.H&&a.eventHandler.listen(a.H,"click",()=>{var b;a.m&&(a.m.value="");null===
(b=a.H)||void 0===b?void 0:b.classList.add("hidden");oK(a);pK(a);qK(a,"click")})},tK=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.F=new Set(b);if(!_ds.D().hash&&c)sK(a,a.F);else{c=new _ds.VC;for(const d of a.F)_ds.UC(c,d)}},uK=async function(a){const b=await _ds.x();for(const c of a.F)b.unregisterIntersectionForElement(c)},vK=function(a){a.L=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},
oK=function(a){var b;for(const c of a.L)c.classList.toggle("hidden",!(null===(b=a.m)||void 0===b||!b.value))},pK=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a)a=c.parentElement,b=null===a||void 0===a?void 0:a.textContent,a&&b&&_ds.Bc(a,_ds.If.j(b))}},sK=async function(a,b){if(a.D){var c=await _ds.x(),d=new _ds.VC,e=f=>{f=
f.target;_ds.UC(d,f);a.F.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},mK=function(a,b){b.defaultPrevented||(b=_ds.Xh(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ac(b,_ds.dc(_ds.Vi(b.href).href)))},nK=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;_ds.pk(a.eventHandler,
a,_ds.He,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.C.removeAttribute("animatable")});_ds.A(a,"animatable","");b=_ds.Dc(a.j`animatable`);b(a.background,"animatable","");b(a.C,"animatable","");a.hasAttribute("collapsed")?(_ds.A(a,"aria-expanded","true",a.h),_ds.A(a,"aria-label","Hide side navigation",a.h),_ds.A(a,"data-title","Hide side navigation",a.h),a.removeAttribute("collapsed"),wK(a,"Expanded book nav")):(a.h.removeAttribute("aria-expanded"),_ds.A(a,"aria-label",
"Show side navigation",a.h),_ds.A(a,"data-title","Show side navigation",a.h),_ds.A(a,"collapsed",""),wK(a,"Collapsed book nav"));await _ds.bj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},qK=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},
bubbles:!0}))},lK=function(a,b){let c=!1;if(a.v)for(const d of a.v.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.A(a,"hidden","",d);return c},xK=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.hj(_ds.D().pathname);a=`[href="${_ds.Vi(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},yK=function(a,b=a){b||(b=a);const c=b.querySelector(".devsite-mobile-nav-bottom");if(c){let d=c.querySelector(".devsite-nav-active");for(;d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.pk(a.eventHandler,d,"devsite-expandable-nav-transition-end",()=>{d&&_ds.A(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement}},AK=
async function(a){a.D&&(a.removeAttribute("user-scrolled"),await _ds.bj(),await zK(a),await a.O,await _ds.x(),await _ds.bj(),await zK(a))},zK=async function(a){if(a.D&&a.v){await _ds.x();var b=a.v.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await BK(a,b))}},BK=async function(a,b){if(a.D){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Fk(b,a,!0).y;await _ds.bj();c&&_ds.A(a,"user-scrolled","")}},wK=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},CK=class extends _ds.C{constructor(){super();this.D=!1;this.H=this.m=this.G=this.v=null;this.L=[];this.eventHandler=new _ds.H;this.R=()=>{};this.F=new Set;this.J=this.M=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.h=_ds.M(gK);this.C=_ds.M(hK);this.O=new Promise(a=>{this.R=a});this.K=new _ds.lk(()=>{this.D&&kK(this)},20)}static get observedAttributes(){return["collapsed",
"fixed","hidden"]}async connectedCallback(){var a,b;this.D=!0;_ds.Fg(this,this.j`animatable`,this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`role`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);_ds.A(this,"role","menu");this.parentNode&&this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.A(this,"hidden","",this.h),_ds.A(this,"hidden","",this.C));const c=await _ds.x();
if(this.M=c.hasFlagAccess(150))null===(a=this.parentElement)||void 0===a?void 0:a.insertBefore(this.h,this.nextSibling),_ds.A(this,"aria-label","Hide side navigation",this.h),_ds.A(this,"data-title","Hide side navigation",this.h),_ds.A(this,"aria-expanded","true",this.h),null===(b=this.parentElement)||void 0===b?void 0:b.insertBefore(this.C,this.nextSibling);if(this.J=c.hasFlagAccess(155))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.m=this.G.querySelector("input[type=text]"),this.H=
this.G.querySelector(".filter-clear-button"),vK(this);kK(this);rK(this);await this.init();tK(this)}disconnectedCallback(){this.D=!1;_ds.K(this.eventHandler);uK(this);this.F.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.A(this,"visually-hidden","",a);a=[this.background,this.h,this.C];for(const b of a)b&&_ds.Hh(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.C.removeAttribute("animatable");this.C.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===
a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.A(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.h,this.C];for(const d of c)d&&(b?_ds.A(this,a,"",d):
d.removeAttribute(a))}"fixed"===a&&this.R()}async init(a=!0){if(this.D){this.C.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.v=this.querySelector(".devsite-mobile-nav-bottom");_ds.A(this,"top-level-nav","");this.v&&this.v.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.A(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.A(this,b,"",
this.background);!this.hasAttribute("hidden")&&a?(xK(this),yK(this),await AK(this)):(await _ds.bj(),await zK(this))}}async Ta(a){var b;a?(a=a.querySelector("nav")||null,xK(this,a),yK(this,a),a&&(await uK(this),this.F.clear(),tK(this,a,!1)),_ds.Ig(this,this.querySelector("nav"),a)):_ds.Fh(this);this.J&&(vK(this),this.m&&(this.m.value="",null===(b=this.H)||void 0===b?void 0:b.classList.add("hidden")));await _ds.bj();await this.init(!1)}};CK.prototype.updateContent=CK.prototype.Ta;
CK.prototype.attributeChangedCallback=CK.prototype.attributeChangedCallback;CK.prototype.disconnectedCallback=CK.prototype.disconnectedCallback;CK.prototype.connectedCallback=CK.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",CK)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
