(function(_ds){var window=this;var rL=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.iq("Botones de acci\u00f3n");return(0,_ds.Q)(a+'"></div>')},sL=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.S(a)+'" data-title="'+_ds.S(a)+'"></button>')},tL=
function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.S(a)+'" data-title="'+_ds.S(a)+'"></button>')},uL=function(a){var b=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.S(a.Zk)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.S(b)+'" data-title="'+_ds.S(b)+'"></button>')},vL=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.S(a)+'" data-title="'+_ds.S(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(I){return I.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;")}function b(I,J,U){switch(I.nodeType){case 1:var G=I.tagName.toLowerCase();J.push("<",G);var ia=I.attributes,xa=ia.length;if(xa){if(U){for(var Aa=[],oa=xa;0<=--oa;)Aa[oa]=ia[oa];Aa.sort(function(la,Fa){return la.name<Fa.name?-1:la.name===Fa.name?0:1});ia=Aa}for(oa=0;oa<xa;++oa)Aa=ia[oa],Aa.specified&&J.push(" ",Aa.name.toLowerCase(),'="',Aa.value.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(B,
"&quot;"),'"')}J.push(">");for(ia=I.firstChild;ia;ia=ia.nextSibling)b(ia,J,U);!I.firstChild&&/^(?:br|link|img)$/.test(G)||J.push("</",G,">");break;case 3:case 4:J.push(a(I.nodeValue))}}function c(I){function J(Y){if("\\"!==Y.charAt(0))return Y.charCodeAt(0);switch(Y.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(Y.substring(2),16)||Y.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(Y.substring(1),
8);default:return Y.charCodeAt(1)}}function U(Y){if(32>Y)return(16>Y?"\\x0":"\\x")+Y.toString(16);Y=String.fromCharCode(Y);if("\\"===Y||"-"===Y||"["===Y||"]"===Y)Y="\\"+Y;return Y}function G(Y){var Z=Y.substring(1,Y.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));Y=[];for(var X=[],ra="^"===Z[0],ba=ra?1:0,pa=Z.length;ba<pa;++ba){var da=Z[ba];switch(da){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":Y.push(da);
continue}da=J(da);if(ba+2<pa&&"-"===Z[ba+1]){var Na=J(Z[ba+2]);ba+=2}else Na=da;X.push([da,Na]);65>Na||122<da||(65>Na||90<da||X.push([Math.max(65,da)|32,Math.min(Na,90)|32]),97>Na||122<da||X.push([Math.max(97,da)&-33,Math.min(Na,122)&-33]))}X.sort(function(Nb,Gd){return Nb[0]-Gd[0]||Gd[1]-Nb[1]});Z=[];da=[NaN,NaN];for(ba=0;ba<X.length;++ba)pa=X[ba],pa[0]<=da[1]+1?da[1]=Math.max(da[1],pa[1]):Z.push(da=pa);X=["["];ra&&X.push("^");X.push.apply(X,Y);for(ba=0;ba<Z.length;++ba)pa=Z[ba],X.push(U(pa[0])),
pa[1]>pa[0]&&(pa[1]+1>pa[0]&&X.push("-"),X.push(U(pa[1])));X.push("]");return X.join("")}function ia(Y){for(var Z=Y.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),X=Z.length,ra=[],ba=0,pa=0;ba<X;++ba){var da=Z[ba];"("===da?++pa:"\\"===da.charAt(0)&&(da=+da.substring(1))&&da<=pa&&(ra[da]=-1)}for(ba=1;ba<ra.length;++ba)-1===ra[ba]&&(ra[ba]=++xa);for(pa=ba=0;ba<X;++ba)da=
Z[ba],"("===da?(++pa,void 0===ra[pa]&&(Z[ba]="(?:")):"\\"===da.charAt(0)&&(da=+da.substring(1))&&da<=pa&&(Z[ba]="\\"+ra[pa]);for(pa=ba=0;ba<X;++ba)"^"===Z[ba]&&"^"!==Z[ba+1]&&(Z[ba]="");if(Y.ignoreCase&&Aa)for(ba=0;ba<X;++ba)da=Z[ba],Y=da.charAt(0),2<=da.length&&"["===Y?Z[ba]=G(da):"\\"!==Y&&(Z[ba]=da.replace(/[a-zA-Z]/g,function(Na){Na=Na.charCodeAt(0);return"["+String.fromCharCode(Na&-33,Na|32)+"]"}));return Z.join("")}for(var xa=0,Aa=!1,oa=!1,la=0,Fa=I.length;la<Fa;++la){var Ga=I[la];if(Ga.ignoreCase)oa=
!0;else if(/[a-z]/i.test(Ga.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Aa=!0;oa=!1;break}}var ua=[];la=0;for(Fa=I.length;la<Fa;++la){Ga=I[la];if(Ga.global||Ga.multiline)throw Error(""+Ga);ua.push("(?:"+ia(Ga)+")")}return new RegExp(ua.join("|"),oa?"gi":"g")}function d(I){var J=0;return function(U){for(var G=null,ia=0,xa=0,Aa=U.length;xa<Aa;++xa)switch(U.charAt(xa)){case "\t":G||(G=[]);G.push(U.substring(ia,xa));ia=I-J%I;for(J+=ia;0<=ia;ia-=16)G.push("                ".substring(0,
ia));ia=xa+1;break;case "\n":J=0;break;default:++J}if(!G)return U;G.push(U.substring(ia));return G.join("")}}function e(I,J,U,G){J&&(I={source:J,Xh:I},U(I),G.push.apply(G,I.ni))}function f(I,J){var U={},G;(function(){for(var Aa=I.concat(J),oa=[],la={},Fa=0,Ga=Aa.length;Fa<Ga;++Fa){var ua=Aa[Fa],Y=ua[3];if(Y)for(var Z=Y.length;0<=--Z;)U[Y.charAt(Z)]=ua;ua=ua[1];Y=""+ua;la.hasOwnProperty(Y)||(oa.push(ua),la[Y]=null)}oa.push(/[\0-\uffff]/);G=c(oa)})();var ia=J.length,xa=function(Aa){for(var oa=Aa.Xh,
la=[oa,"pln"],Fa=0,Ga=Aa.source.match(G)||[],ua={},Y=0,Z=Ga.length;Y<Z;++Y){var X=Ga[Y],ra=ua[X],ba=void 0;if("string"===typeof ra)var pa=!1;else{var da=U[X.charAt(0)];if(da)ba=X.match(da[1]),ra=da[0];else{for(pa=0;pa<ia;++pa)if(da=J[pa],ba=X.match(da[1])){ra=da[0];break}ba||(ra="pln")}!(pa=5<=ra.length&&"lang-"===ra.substring(0,5))||ba&&"string"===typeof ba[1]||(pa=!1,ra="src");pa||(ua[X]=ra)}da=Fa;Fa+=X.length;if(pa){pa=ba[1];var Na=X.indexOf(pa),Nb=Na+pa.length;ba[2]&&(Nb=X.length-ba[2].length,
Na=Nb-pa.length);ra=ra.substring(5);e(oa+da,X.substring(0,Na),xa,la);e(oa+da+Na,pa,l(ra,pa),la);e(oa+da+Nb,X.substring(Nb),xa,la)}else la.push(oa+da,ra)}Aa.ni=la};return xa}function g(I){var J=[],U=[];I.tripleQuotedStrings?J.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):I.multiLineStrings?J.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):J.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);I.verbatimStrings&&U.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var G=I.hashComments;G&&(I.cStyleComments?(1<G?J.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):J.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),U.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):J.push(["com",
/^#[^\r\n]*/,null,"#"]));I.cStyleComments&&(U.push(["com",/^\/\/[^\r\n]*/,null]),U.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));I.regexLiterals&&U.push(["lang-regex",new RegExp("^"+n+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);I=I.keywords.replace(/^\s+|\s+$/g,"");I.length&&U.push(["kwd",new RegExp("^(?:"+I.replace(/\s+/g,"|")+")\\b"),null]);J.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);U.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,
null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(J,U)}function h(I){function J(ze){if(ze>la){Fa&&Fa!==Ga&&(oa.push("</span>"),Fa=null);!Fa&&Ga&&(Fa=Ga,oa.push('<span class="',Fa,'">'));var gl=a(Z(U.substring(la,ze))).replace(da?ra:X,"$1&#160;");da=pa.test(gl);oa.push(gl.replace(ba,fl));la=ze}}var U=I.source,G=I.Cl,ia=I.ni,xa=I.Oi,Aa=I.hj,
oa=[],la=0,Fa=null,Ga=null,ua=0,Y=0,Z=d(window.PR_TAB_WIDTH),X=/([\r\n ]) /g,ra=/(^| ) /gm,ba=/\r\n?|\n/g,pa=/[ \r\n]$/,da=!0,Na=window._pr_isIE6();Aa=Na?Aa&&"PRE"===Aa.tagName?6===Na?"&#160;\r\n":7===Na?"&#160;<br />\r":8===Na?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(xa){var Nb=[];for(Na=0;10>Na;++Na)Nb[Na]=Aa+'</li><li class="L'+Na+'">';var Gd="number"===typeof xa?xa-1:0;oa.push('<ol class="linenums"><li class="L',Gd%10,'"');Gd&&oa.push(' value="',Gd+1,'"');oa.push(">");var fl=function(){var ze=
Nb[++Gd%10];return Fa?"</span>"+ze+'<span class="'+Fa+'">':ze}}else fl=Aa;for(;;)if(ua<G.length&&(Y<ia.length?G[ua]<=ia[Y]:1))J(G[ua]),Fa&&(oa.push("</span>"),Fa=null),oa.push(G[ua+1]),ua+=2;else if(Y<ia.length)J(ia[Y]),Ga=ia[Y+1],Y+=2;else break;J(U.length);Fa&&oa.push("</span>");xa&&oa.push("</li></ol>");I.Gg=oa.join("")}function k(I,J){for(var U=J.length;0<=--U;){var G=J[U];Ca.hasOwnProperty(G)?"console"in window&&console.warn("cannot override language handler %s",G):Ca[G]=I}}function l(I,J){I&&
Ca.hasOwnProperty(I)||(I=/^\s*</.test(J)?"default-markup":"default-code");return Ca[I]}function m(I){var J=I.gj,U=I.Gi;I.Gg=J;try{var G=J.match(Qa);J=[];var ia=0,xa=[];if(G)for(var Aa=0,oa=G.length;Aa<oa;++Aa){var la=G[Aa];if(1<la.length&&"<"===la.charAt(0)){if(!za.test(la))if(ka.test(la))J.push(la.substring(9,la.length-3)),ia+=la.length-12;else if(hb.test(la))J.push("\n"),++ia;else if(0<=la.indexOf("nocode")&&la.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Fa=
la.match(ta)[2],Ga=1;var ua=Aa+1;a:for(;ua<oa;++ua){var Y=G[ua].match(ta);if(Y&&Y[2]===Fa)if("/"===Y[1]){if(0===--Ga)break a}else++Ga}ua<oa?(xa.push(ia,G.slice(Aa,ua+1).join("")),Aa=ua):xa.push(ia,la)}else xa.push(ia,la)}else{Ga=la;var Z=Ga.indexOf("&");if(0>Z)var X=Ga;else{for(--Z;0<=(Z=Ga.indexOf("&#",Z+1));){var ra=Ga.indexOf(";",Z);if(0<=ra){var ba=Ga.substring(Z+3,ra),pa=10;ba&&"x"===ba.charAt(0)&&(ba=ba.substring(1),pa=16);var da=parseInt(ba,pa);isNaN(da)||(Ga=Ga.substring(0,Z)+String.fromCharCode(da)+
Ga.substring(ra+1))}}X=Ga.replace(z,"<").replace(O,">").replace(E,"'").replace(T,'"').replace(Ja," ").replace(wa,"&")}J.push(X);ia+=X.length}}var Na=J.join("");I.source=Na;I.Xh=0;I.Cl=xa;l(U,Na)(I);h(I)}catch(Nb){"console"in window&&console.log(Nb&&Nb.stack?Nb.stack:Nb)}}var n=function(){for(var I="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
J="(?:^^|[+-]",U=0;U<I.length;++U)J+="|"+I[U].replace(/([^=<>:&a-z])/g,"\\$1");return J+")\\s*"}(),t=/&/g,v=/</g,w=/>/g,B=/"/g,z=/&lt;/g,O=/&gt;/g,E=/&apos;/g,T=/&quot;/g,wa=/&amp;/g,Ja=/&nbsp;/g,Ba=/[\r\n]/g,Ka=null,Qa=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),za=/^\x3c!--/,ka=/^<!\[CDATA\[/,hb=/^<br\b/i,ta=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ob=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ca={};k(ob,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(I,J,U){I={gj:I,Gi:J,Oi:U};m(I);return I.Gg};window.prettyPrint=function(I){function J(){for(var Ga=
window.PR_SHOULD_USE_CONTINUATION?oa.now()+250:Infinity;la<G.length&&oa.now()<Ga;la++){var ua=G[la];if(ua.className&&0<=ua.className.indexOf("prettyprint")){var Y=ua.className.match(/\blang-(\w+)\b/);Y&&(Y=Y[1]);for(var Z=!1,X=ua.parentNode;X;X=X.parentNode)if(("pre"===X.tagName||"code"===X.tagName||"xmp"===X.tagName)&&X.className&&0<=X.className.indexOf("prettyprint")){Z=!0;break}if(!Z){X=ua;null===Ka&&(Z=document.createElement("PRE"),Z.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
Ka=!/</.test(Z.innerHTML));if(Ka)if(Z=X.innerHTML,"XMP"===X.tagName)Z=a(Z);else{if("PRE"!==X.tagName&&Ba.test(Z)){var ra="";X.currentStyle?ra=X.currentStyle.whiteSpace:window.getComputedStyle&&(ra=window.getComputedStyle(X,null).whiteSpace);X=!ra||"pre"===ra}else X=!0;X||(Z=Z.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{Z=[];for(X=X.firstChild;X;X=X.nextSibling)b(X,Z);Z=Z.join("")}Z=Z.replace(/(?:\r\n?|\n)$/,"");X=ua.className.match(/\blinenums\b(?::(\d+))?/);Fa={gj:Z,
Gi:Y,hj:ua,Oi:X?X[1]&&X[1].length?+X[1]:!0:!1};m(Fa);if(ua=Fa.Gg)if(Y=Fa.hj,"XMP"===Y.tagName){Z=document.createElement("PRE");for(X=0;X<Y.attributes.length;++X)ra=Y.attributes[X],ra.specified&&("class"===ra.name.toLowerCase()?Z.className=ra.value:Z.setAttribute(ra.name,ra.value));Z.innerHTML=ua;Y.parentNode.replaceChild(Z,Y)}else Y.innerHTML=ua}}}la<G.length?setTimeout(J,250):I&&I()}for(var U=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
G=[],ia=0;ia<U.length;++ia)for(var xa=0,Aa=U[ia].length;xa<Aa;++xa)G.push(U[ia][xa]);U=null;var oa=Date;oa.now||(oa={now:function(){return(new Date).getTime()}});var la=0,Fa;J()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[window.PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[window.PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[window.PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[window.PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[window.PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],
[window.PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],[window.PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[window.PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[window.PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[window.PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[window.PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);
window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[window.PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[window.PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[window.PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[window.PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[window.PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[window.PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[window.PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[window.PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],
[window.PR.PR_LITERAL,/^(?:true|false|null)\b/],[window.PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[window.PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[window.PR.PR_COMMENT,/^\/\/.*/],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[window.PR.PR_STRING,/'.'/],[window.PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[window.PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[window.PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[window.PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),
["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[window.PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[window.PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[window.PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[window.PR.PR_LITERAL,
/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_]\w*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[window.PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[window.PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[window.PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);window.PR.registerLangHandler(window.PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[window.PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[window.PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[window.PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[window.PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[window.PR.PR_KEYWORD,
/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],[window.PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[window.PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[window.PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[window.PR.PR_PLAIN,
/^[$a-zA-Z_][\w$]*/],[window.PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[window.PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[window.PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[window.PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_][\w-]*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[window.PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[window.PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[window.PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[window.PR.PR_LITERAL,/^(?:true|false|nil)\b/,
null],[window.PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[window.PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[window.PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[window.PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[window.PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[window.PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[window.PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[window.PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[window.PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[window.PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[window.PR.PR_PUNCTUATION,/^(?:\[|\])/]]),
["vb","vbs"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[window.PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[window.PR.PR_COMMENT,/^--[^\r\n]*/],[window.PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[window.PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[window.PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[window.PR.PR_LITERAL,
/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],[window.PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[window.PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[window.PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[window.PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[window.PR.PR_PLAIN,
/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[window.PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[window.PR.PR_TYPE,/^[&]\S+/,null,"&"],[window.PR.PR_TYPE,/^!\S*/,null,"!"],[window.PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[window.PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],
[window.PR.PR_PUNCTUATION,/^-/],[window.PR.PR_KEYWORD,/^\w+:[ \r\n]/],[window.PR.PR_PLAIN,/^\w+/]]),["yaml","yml"]);var wL=window;var xL=function(a){_ds.cj().then(()=>{a.prettyPrint()})},zL=function(a){a.D&&a.eventHandler.listen(a.D,"click",()=>void a.setAttribute("dark-code",""));a.F&&a.eventHandler.listen(a.F,"click",()=>void a.removeAttribute("dark-code"));a.m&&a.eventHandler.listen(a.m,"click",()=>void yL(a));a.v&&a.eventHandler.listen(a.v,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"C\u00f3digo de ejemplo",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.VE(c,b):
_ds.UE([a],b)})},yL=async function(a){var b,c=a.querySelector("pre:not(.devsite-copy-hide)");if(c&&(c=[...c.childNodes],_ds.No(document.body,c),a.C)){const d=new _ds.rk;null===(b=a.m)||void 0===b?void 0:b.setAttribute("aria-label","C\u00f3digo de ejemplo copiado al portapapeles");_ds.pk(a.eventHandler,a.C,"transitionend",()=>{d.j()});await d.promise;_ds.pk(a.eventHandler,a.C,"transitionend",()=>{var e;null===(e=a.m)||void 0===e?void 0:e.setAttribute("aria-label",a.G)})}},AL=class extends _ds.C{constructor(){super(["devsite-snackbar"]);
this.C=this.F=this.v=this.D=this.m=this.h=null;this.L=!1;this.G="";this.eventHandler=new _ds.H;this.J=new _ds.rk;this.H=new _ds.Yl;this.K=new _ds.AB(_ds.EB(_ds.DB()));_ds.Fg(this,(0,_ds.u)`no-toggle`)}static get observedAttributes(){return["dark-code"]}whenReady(){return this.J.promise}async connectedCallback(){var a=await _ds.x();if(!this.L){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&
!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.G=c?`${"Copiar c\u00f3digo de ejemplo"}: ${c}`:"Copiar c\u00f3digo de ejemplo";b.classList.contains("devsite-disable-code-toggle")&&(_ds.A(this,
"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}xL(this);
this.L=!0}if((d=this.querySelector(".devsite-dark-code-default"))||this.H.get("pref_dark-code"))this.setAttribute("dark-code",""),d&&d.classList.remove("devsite-dark-code-default");this.J.j();try{await a.intersectionEnterForElement(this)}catch(k){if("IntersectionObserver not supported"!==k.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.h=a;else{this.h=_ds.M(rL);var e,f,g,h;this.hasAttribute("scope")&&(this.v=_ds.M(vL,{label:"Abrir c\u00f3digo de ejemplo en JSFiddle"}),
(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.v.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||this.getAttribute("jsfiddle-title")}`),null===(e=this.h)||void 0===e?void 0:e.appendChild(this.v));this.hasAttribute("no-toggle")||(this.D=_ds.M(sL,{label:"Tema de c\u00f3digo oscuro"}),null===(f=this.h)||void 0===f?void 0:f.appendChild(this.D),this.F=_ds.M(tL,{label:"Tema de c\u00f3digo claro"}),null===(g=this.h)||void 0===g?void 0:g.appendChild(this.F));
this.hasAttribute("no-copy")||(e=this.getAttribute("data-copy-event-label"),f="Click To Copy",e&&(f+=`: ${e}`),this.m=_ds.M(uL,{label:this.G,Zk:f}),null===(h=this.h)||void 0===h?void 0:h.appendChild(this.m));this.prepend(this.h)}zL(this);this.C=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.x()).unregisterIntersectionForElement(this);this.h&&this.removeChild(this.h);_ds.K(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");
a=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;var b=a;a=c.innerHTML;b=null!==b&&void 0!==b?b:"";a=a.replace(/(&#39;)/g,"'");a=wL.prettyPrintOne(a,b,void 0);_ds.Bc(c,this.K.j(a));c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.H.set("pref_dark-code","1");await _ds.bj();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>
f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.H.remove("pref_dark-code");await _ds.bj();e=[...document.querySelectorAll("devsite-code[dark-code]")];for(d of e)d.removeAttribute("dark-code")}}};AL.prototype.attributeChangedCallback=AL.prototype.attributeChangedCallback;AL.prototype.disconnectedCallback=AL.prototype.disconnectedCallback;AL.prototype.connectedCallback=AL.prototype.connectedCallback;AL.prototype.whenReady=AL.prototype.whenReady;try{window.customElements.define("devsite-code",AL)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
