(function(_ds){var window=this;var oX=function(a){var b=a.bh,c=a.Db,d=a.Wk;a=a.cm;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">En esta p\u00e1gina</span></span>';c&&(e=e+'<button type="button" title="'+_ds.kq("Expandir o contraer contenido"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=
b[h];e+='<li class="devsite-nav-item"'+(c&&g.index<a?" visible":"")+'><a href="#'+_ds.T(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.T(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.T(h)+'" track-metadata-link-destination="#'+_ds.T(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(g.text)+"</span></a>";
if(_ds.$p(g.children).length){e+='<ul class="devsite-nav-list">';g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.T(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.T(h)+"."+_ds.T(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+
_ds.T(h)+"."+_ds.T(l)+'" track-metadata-link-destination="#'+_ds.T(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Probar</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Pru\u00e9balo</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.kq("Expandir o contraer contenido"),e+='"></button></li>');return(0,_ds.Q)(e+"</ul>")};var qX=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Db?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),pX(a,b),a.H=!0):a.jb()}},sX=async function(a){await rX(a);if(a.h){var b=`#${a.h.id}`,c=encodeURI(b);b=a.F.get(b)||a.F.get(c);a.v!==b&&(a.v&&a.v.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.v=b))}},tX=function(a){a.Db||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
()=>{a.K.j()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{qX(a)})},uX=async function(a){if("IntersectionObserver"in _ds.Eh()){a.C&&a.C.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await window.customElements.whenDefined("devsite-header"),(b=Number(b.getAttribute("top-row--height"))+Number(b.getAttribute("bottom-row--height")))&&(c=b));a.C=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.D.add(e.target):a.D.delete(e.target);a.K.j()},
{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.J.j()},rX=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),b=c.D());c=a.m.findIndex(e=>a.D.has(e)&&e.getBoundingClientRect().top>=b);const d=a.m[c];if(d){const e=await vX();d.getBoundingClientRect().top-b>e&&0<c?a.h=a.m[c-1]:a.h=d}else a.h&&a.h.getBoundingClientRect().top>window.innerHeight&&(c=a.m.indexOf(a.h),0<c&&(a.h=a.m[c-1]))},pX=function(a,b){const c=[];
let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.m=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>wX(f));for(const [f,g]of a.m.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-
1].children.push(b):c.push(b);_ds.Ya(a.G,c,a.L.bind(a))&&a.H||(c.length?(xX(a,c),a.show(),a.Db||yX(a)):a.jb(),a.G=c)},wX=function(a){return _ds.pj.find(b=>!!_ds.ai(a,null,b,6))||_ds.ai(a,"devsite-selector",null,6)||_ds.ai(a,null,"devsite-dialog",3)?!1:!0},xX=function(a,b){const c=_ds.M(oX,{bh:b,Db:a.Db,Wk:!!document.body.querySelector("devsite-apix, .devsite-apix"),cm:5});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.F.set(e,b);a.F.set(f,b)}_ds.Jh(a);
a.Db&&_ds.y(a,"hidden","",c);a.appendChild(c);if(a.Db){if(8<=a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.y(a,"expanded","")});_ds.y(a,"expandable","")}setTimeout(()=>{c.removeAttribute("hidden")},0)}},yX=async function(a){await a.J.promise;if(a.C){a.C.disconnect();a.D.clear();a.v&&a.v.classList.remove("devsite-nav-active");
a.v=null;for(const b of a.m)a.C.observe(b)}},vX=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),a=c.D(),b=c.K());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},zX=class extends _ds.A{constructor(){super();this.eventHandler=new _ds.I;this.J=new _ds.wk;this.D=new Set;this.F=new Map;this.R=new _ds.qk(()=>void qX(this),16);this.K=new _ds.qk(()=>void sX(this),33);this.h=this.v=null;this.m=[];this.H=
!1;this.C=null;this.Db=!1;this.G=[];_ds.Lg(this,(0,_ds.Sb)`disabled`,(0,_ds.Sb)`has-sidebar`,(0,_ds.Sb)`hidden`,(0,_ds.Sb)`expandable`,(0,_ds.Sb)`expanded`,(0,_ds.Sb)`visible`)}static get observedAttributes(){return["max-height","offset"]}connectedCallback(){this.Db=this.hasAttribute("devsite-toc-embedded");qX(this);tX(this)}disconnectedCallback(){this.jb();this.H=!1;_ds.K(this.eventHandler)}Ie(a){a=a&&"false"===a.toLowerCase();this.G=[];_ds.Jh(this);a?(_ds.y(this,"disabled",""),this.jb()):(this.removeAttribute("disabled"),
this.show(),this.R.j())}jb(){_ds.Jh(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.y(this,"hidden","");if(!this.Db){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.y(this,"visible","");if(!this.Db){const a=document.querySelector(".devsite-main-content");a&&_ds.y(this,
"has-sidebar","",a);uX(this)}}L(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.Ya(a.children,b.children,this.L.bind(this));return c&&a.id===b.id&&a.text===b.text}};zX.prototype.renderUpdatedContent=zX.prototype.Ie;zX.prototype.disconnectedCallback=zX.prototype.disconnectedCallback;zX.prototype.connectedCallback=zX.prototype.connectedCallback;try{window.customElements.define("devsite-toc",zX)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
