(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var QQ=_ds.Wg(function(){return!_ds.Ad||0<=_ds.Aa(_ds.XE,9)}),RQ=_ds.Wg(function(){return _ds.Ed||_ds.Bd||_ds.Dd&&0<=_ds.Aa(_ds.XE,10)||_ds.Ad&&0<=_ds.Aa(_ds.XE,10)}),TQ=function(a,b){QQ()&&(b=RQ()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Ak(a,SQ(),b))},SQ=_ds.Wg(function(){return _ds.Ad&&9==_ds.Xd?"-ms-transform":"transform"});var WQ=function(a){a.m=UQ(a,".devsite-top-logo-row-wrapper-wrapper");a.h=UQ(a,".devsite-collapsible-section");a.C=UQ(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.m}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.C}`);VQ(a)},VQ=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.C&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.L&&(_ds.Ak(b,"transform",`translate3d(0, -${a.offset}px, 0)`),XQ(a),a.L=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.D()}px`)},YQ=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.K(a.G);a.F&&window.cancelAnimationFrame(a.F);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.hh(b.offsetWidth,b.offsetHeight);b=new _ds.hh(c.offsetWidth,c.offsetHeight);var f=_ds.Tk(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Ak(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});TQ(c,a.hasAttribute("search-active")?0:e);_ds.uk(a.G,d,_ds.Oe,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),TQ(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.F=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(QQ()){var m=RQ()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.Ak(d,SQ(),m)}TQ(c,k)})}},ZQ=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null===a||void 0===a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.gj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},aR=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.W;_ds.ai(b.target,null,"devsite-top-logo-row-middle",void 0)&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>$Q(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{$Q(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},bR=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},XQ=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},$Q=function(a){window.requestAnimationFrame(()=>
a.J.j())},UQ=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},cR=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},dR=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Mg(a,c,b))},eR=class extends _ds.A{constructor(){super(...arguments);this.eventHandler=new _ds.I;this.L=
-1;this.G=new _ds.I;this.F=0;this.H=new MutationObserver(()=>WQ(this));this.J=new _ds.qk(()=>{WQ(this);XQ(this)},15);this.v=void 0;this.offset=this.C=this.h=this.m=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;VQ(this);break;case "search-active":YQ(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),ZQ(this,a)}}connectedCallback(){aR(this);bR(this);XQ(this);WQ(this);this.H.observe(this,{childList:!0,subtree:!0});VQ(this);const a=_ds.F();this.v=_ds.Hi(_ds.Ji(a.href),"authuser")}disconnectedCallback(){_ds.K(this.eventHandler);this.H.disconnect()}D(){return this.m+this.h-this.offset}K(){return this.m+this.h}Ua(a){this.updated=!1;if(a){dR(this,a,".devsite-header-upper-tabs");
dR(this,a,".devsite-collapsible-section");dR(this,a,".devsite-product-name-wrapper");dR(this,a,"devsite-language-selector");dR(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&cR(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(cR(c,b),c=_ds.F(),c=_ds.Hi(_ds.Ji(c.href),"authuser"),c!==this.v&&(this.v=c,b.refresh()));_ds.Mg(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Mg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Jh(this),this.appendChild(a));bR(this);$Q(this)}};try{window.customElements.define("devsite-header",eR)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
