(function(_ds){var window=this;var VJ=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},WJ=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')};var XJ="onpointerover"in window?"pointerover":"mouseover",YJ=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.y(a,"visually-hidden","",c))},dK=function(a){a.eventHandler.listen(a,"click",b=>{var c;if(!b.defaultPrevented){const e=b.target;"devsite-close-nav"===e.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})):_ds.y(a,"top-level-nav",""));if(e.hasAttribute("menu")){const f=e.getAttribute("menu");f&&ZJ(a,f)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(e.classList.contains("devsite-nav-toggle")||e.classList.contains("devsite-nav-title-no-path")||(null===(c=e.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(e)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0}));var d;e instanceof Element&&e.matches("a.devsite-nav-title")?d=e:d=_ds.ai(e,"a","devsite-nav-title");d&&!d.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[XJ,"focusin"],b=>void $J(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.m&&(ZJ(a,"_book")?a.removeAttribute("top-level-nav"):_ds.y(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.K.j());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.K.j()});a.eventHandler.listen(a,"scroll",()=>{_ds.y(a,"user-scrolled","")});a.eventHandler.listen(a.h,"click",()=>{aK(a)});a.C&&a.L.length&&a.eventHandler.listen(a.C,"keyup",()=>{var b,c,d,e,f,g;bK(a);cK(a);const h=null===(c=null===(b=a.C)||void 0===b?void 0:b.value)||void 0===c?void 0:c.trim().toLowerCase();if(h){null===(d=a.H)||void 0===d?void 0:d.classList.remove("hidden");for(const l of a.L){b=l.querySelectorAll(".devsite-nav-text");
c=l.classList.contains("devsite-nav-expandable");var k=d=!1;if(h&&c&&(null===(f=null===(e=l.querySelector(".devsite-nav-text"))||void 0===e?void 0:e.textContent)||void 0===f?0:f.toLowerCase().includes(h)))k=d=!0;else for(const m of b)h&&(null===(g=m.textContent)||void 0===g?0:g.toLowerCase().includes(h))&&(d=!0);if(!0===d){l.classList.remove("hidden");if(k){b=Array.from(l.querySelectorAll(".devsite-nav-item"));for(const m of b)m.classList.remove("hidden")}b=void 0;(d=l.querySelector(".devsite-nav-text"))&&
(c=null===(b=d.textContent)||void 0===b?void 0:b.replace(new RegExp(`(${h})`,"ig"),"<mark>$1</mark>"))&&_ds.Fc(d,_ds.Pf.j(c))}}}else null===(k=a.H)||void 0===k?void 0:k.classList.add("hidden")});a.H&&a.eventHandler.listen(a.H,"click",()=>{var b;a.C&&(a.C.value="");null===(b=a.H)||void 0===b?void 0:b.classList.add("hidden");bK(a);cK(a)})},fK=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.F=new Set(b);if(!_ds.F().hash&&c)eK(a,a.F);else{c=new _ds.iC;for(const d of a.F)_ds.hC(c,
d)}},gK=async function(a){const b=await _ds.u();for(const c of a.F)b.unregisterIntersectionForElement(c)},hK=function(a){a.L=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},bK=function(a){var b;for(const c of a.L)c.classList.toggle("hidden",!(null===(b=a.C)||void 0===b||!b.value))},cK=function(a){if(a.querySelector("mark")){a=Array.from(a.querySelectorAll(".devsite-nav-text > mark"));for(const b of a){a=b.parentElement;
const c=null===a||void 0===a?void 0:a.textContent;a&&c&&_ds.Fc(a,_ds.Pf.j(c))}}},eK=async function(a,b){if(a.D){var c=await _ds.u(),d=new _ds.iC,e=f=>{f=f.target;_ds.hC(d,f);a.F.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},$J=function(a,b){b.defaultPrevented||(b=_ds.$h(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ec(b,_ds.ic(_ds.$i(b.href).href)))},aK=async function(a){var b=
document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;_ds.uk(a.eventHandler,a,_ds.Oe,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.v.removeAttribute("animatable")});_ds.y(a,"animatable","");b=_ds.Hc(a.j`animatable`);b(a.background,"animatable","");b(a.v,"animatable","");a.hasAttribute("collapsed")?(_ds.y(a,"aria-expanded","true",a.h),_ds.y(a,"aria-label","Ocultar panel de navegaci\u00f3n lateral",
a.h),_ds.y(a,"data-title","Ocultar panel de navegaci\u00f3n lateral",a.h),a.removeAttribute("collapsed"),iK(a,"Expanded book nav")):(a.h.removeAttribute("aria-expanded"),_ds.y(a,"aria-label","Mostrar panel de navegaci\u00f3n lateral",a.h),_ds.y(a,"data-title","Mostrar panel de navegaci\u00f3n lateral",a.h),_ds.y(a,"collapsed",""),iK(a,"Collapsed book nav"));await _ds.gj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*
b)},ZJ=function(a,b){let c=!1;if(a.m)for(const d of a.m.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.y(a,"hidden","",d);return c},jK=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.mj(_ds.F().pathname);a=`[href="${_ds.$i(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},kK=function(a,b=a){b||(b=a);const c=b.querySelector(".devsite-mobile-nav-bottom");if(c){let d=c.querySelector(".devsite-nav-active");for(;d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.uk(a.eventHandler,d,"devsite-expandable-nav-transition-end",()=>{d&&_ds.y(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement}},mK=
async function(a){a.D&&(a.removeAttribute("user-scrolled"),await _ds.gj(),await lK(a),await a.O,await _ds.u(),await _ds.gj(),await lK(a))},lK=async function(a){if(a.D&&a.m){await _ds.u();var b=a.m.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await nK(a,b))}},nK=async function(a,b){if(a.D){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Kk(b,a,!0).y;await _ds.gj();c&&_ds.y(a,"user-scrolled","")}},iK=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},oK=class extends _ds.A{constructor(){super();this.D=!1;this.H=this.C=this.G=this.m=null;this.L=[];this.eventHandler=new _ds.I;this.R=()=>{};this.F=new Set;this.J=this.M=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.h=_ds.M(VJ);this.v=_ds.M(WJ);this.O=new Promise(a=>{this.R=a});this.K=new _ds.qk(()=>{this.D&&YJ(this)},20)}static get observedAttributes(){return["collapsed",
"fixed","hidden"]}async connectedCallback(){var a,b;this.D=!0;_ds.Lg(this,this.j`animatable`,this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`role`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);_ds.y(this,"role","menu");this.parentNode&&this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.y(this,"hidden","",this.h),_ds.y(this,"hidden","",this.v));const c=await _ds.u();
if(this.M=c.hasFlagAccess(150))null===(a=this.parentElement)||void 0===a?void 0:a.insertBefore(this.h,this.nextSibling),_ds.y(this,"aria-label","Ocultar panel de navegaci\u00f3n lateral",this.h),_ds.y(this,"data-title","Ocultar panel de navegaci\u00f3n lateral",this.h),_ds.y(this,"aria-expanded","true",this.h),null===(b=this.parentElement)||void 0===b?void 0:b.insertBefore(this.v,this.nextSibling);if(this.J=c.hasFlagAccess(155))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.C=this.G.querySelector("input[type=text]"),
this.H=this.G.querySelector(".filter-clear-button"),hK(this);YJ(this);dK(this);await this.init();fK(this)}disconnectedCallback(){this.D=!1;_ds.K(this.eventHandler);gK(this);this.F.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.y(this,"visually-hidden","",a);a=[this.background,this.h,this.v];for(const b of a)b&&_ds.B(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.v.removeAttribute("animatable");this.v.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===
a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.y(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.h,this.v];for(const d of c)d&&(b?_ds.y(this,a,"",d):
d.removeAttribute(a))}"fixed"===a&&this.R()}async init(a=!0){if(this.D){this.v.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.m=this.querySelector(".devsite-mobile-nav-bottom");_ds.y(this,"top-level-nav","");this.m&&this.m.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.y(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.y(this,b,"",
this.background);!this.hasAttribute("hidden")&&a?(jK(this),kK(this),await mK(this)):(await _ds.gj(),await lK(this))}}async Ua(a){var b;a?(a=a.querySelector("nav")||null,jK(this,a),kK(this,a),a&&(await gK(this),this.F.clear(),fK(this,a,!1)),_ds.Mg(this,this.querySelector("nav"),a)):_ds.Jh(this);this.J&&(hK(this),this.C&&(this.C.value="",null===(b=this.H)||void 0===b?void 0:b.classList.add("hidden")));await _ds.gj();await this.init(!1)}};oK.prototype.updateContent=oK.prototype.Ua;
oK.prototype.attributeChangedCallback=oK.prototype.attributeChangedCallback;oK.prototype.disconnectedCallback=oK.prototype.disconnectedCallback;oK.prototype.connectedCallback=oK.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",oK)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
